// Auto-generated by build/build_data.py — S&P Global connector data as of 2026-06-12
window.COMP_DATA = {
 "as_of": "2026-06-12",
 "price_date": "2026-06-12",
 "fx_note": "FX ~2026-06-12: GBPUSD 1.3368, EURUSD 1.1537, EURSEK 10.92.",
 "sectors": [
  "Exchanges",
  "Info Services",
  "Payments / Fintech",
  "M&A Boutiques",
  "Alternatives",
  "Traditionals",
  "Wealth / Brokers"
 ],
 "rows": [
  {
   "id": "CME",
   "ticker": "CME US",
   "name": "CME Group Inc.",
   "sector": "Exchanges",
   "price": 269.53,
   "price_ccy": "USD",
   "eps_ccy": "USD",
   "fx": null,
   "eps_src": "Normalized",
   "offcycle": false,
   "price_eps_ccy": 269.53,
   "fy_labels": [
    2026,
    2027,
    2028
   ],
   "eps": [
    12.28,
    12.92,
    13.84
   ],
   "rev": [
    7044.1,
    7345.0,
    7769.0
   ],
   "n_est": [
    15,
    15,
    8
   ],
   "pe": [
    22.0,
    20.9,
    19.5
   ],
   "eps_cagr": 6.2,
   "rev_cagr": 5.0
  },
  {
   "id": "ICE",
   "ticker": "ICE US",
   "name": "Intercontinental Exchange, Inc.",
   "sector": "Exchanges",
   "price": 140.53,
   "price_ccy": "USD",
   "eps_ccy": "USD",
   "fx": null,
   "eps_src": "Normalized",
   "offcycle": false,
   "price_eps_ccy": 140.53,
   "fy_labels": [
    2026,
    2027,
    2028
   ],
   "eps": [
    8.14,
    8.81,
    9.72
   ],
   "rev": [
    10975.5,
    11530.5,
    12211.3
   ],
   "n_est": [
    14,
    15,
    8
   ],
   "pe": [
    17.3,
    16.0,
    14.5
   ],
   "eps_cagr": 9.3,
   "rev_cagr": 5.5
  },
  {
   "id": "NDAQ",
   "ticker": "NDAQ US",
   "name": "Nasdaq, Inc.",
   "sector": "Exchanges",
   "price": 88.98,
   "price_ccy": "USD",
   "eps_ccy": "USD",
   "fx": null,
   "eps_src": "Normalized",
   "offcycle": false,
   "price_eps_ccy": 88.98,
   "fy_labels": [
    2026,
    2027,
    2028
   ],
   "eps": [
    3.94,
    4.44,
    5.07
   ],
   "rev": [
    5766.3,
    6252.4,
    6777.8
   ],
   "n_est": [
    16,
    16,
    8
   ],
   "pe": [
    22.6,
    20.1,
    17.5
   ],
   "eps_cagr": 13.4,
   "rev_cagr": 8.4
  },
  {
   "id": "CBOE",
   "ticker": "CBOE US",
   "name": "Cboe Global Markets, Inc.",
   "sector": "Exchanges",
   "price": 294.91,
   "price_ccy": "USD",
   "eps_ccy": "USD",
   "fx": null,
   "eps_src": "Normalized",
   "offcycle": false,
   "price_eps_ccy": 294.91,
   "fy_labels": [
    2026,
    2027,
    2028
   ],
   "eps": [
    13.75,
    14.72,
    16.14
   ],
   "rev": [
    2805.2,
    2907.3,
    3025.3
   ],
   "n_est": [
    12,
    12,
    5
   ],
   "pe": [
    21.5,
    20.0,
    18.3
   ],
   "eps_cagr": 8.3,
   "rev_cagr": 3.8
  },
  {
   "id": "LSE:LSEG",
   "ticker": "LSEG LN",
   "name": "London Stock Exchange Group plc",
   "sector": "Exchanges",
   "price": 90.1,
   "price_ccy": "GBP",
   "eps_ccy": "GBP",
   "fx": null,
   "eps_src": "Normalized",
   "offcycle": false,
   "price_eps_ccy": 90.1,
   "fy_labels": [
    2026,
    2027,
    2028
   ],
   "eps": [
    4.74,
    5.38,
    6.05
   ],
   "rev": [
    9876.6,
    10506.1,
    11191.6
   ],
   "n_est": [
    12,
    12,
    11
   ],
   "pe": [
    19.0,
    16.7,
    14.9
   ],
   "eps_cagr": 13.0,
   "rev_cagr": 6.4
  },
  {
   "id": "XTRA:DB1",
   "ticker": "DB1 GY",
   "name": "Deutsche B\u00f6rse AG",
   "sector": "Exchanges",
   "price": 249.5,
   "price_ccy": "EUR",
   "eps_ccy": "EUR",
   "fx": null,
   "eps_src": "Normalized",
   "offcycle": false,
   "price_eps_ccy": 249.5,
   "fy_labels": [
    2026,
    2027,
    2028
   ],
   "eps": [
    12.4,
    13.31,
    14.67
   ],
   "rev": [
    6443.5,
    6712.8,
    7165.7
   ],
   "n_est": [
    9,
    1,
    8
   ],
   "pe": [
    20.1,
    18.7,
    17.0
   ],
   "eps_cagr": 8.8,
   "rev_cagr": 5.5
  },
  {
   "id": "ENXTPA:ENX",
   "ticker": "ENX FP",
   "name": "Euronext N.V.",
   "sector": "Exchanges",
   "price": 148.2,
   "price_ccy": "EUR",
   "eps_ccy": "EUR",
   "fx": null,
   "eps_src": "Normalized",
   "offcycle": false,
   "price_eps_ccy": 148.2,
   "fy_labels": [
    2026,
    2027,
    2028
   ],
   "eps": [
    7.95,
    8.69,
    9.37
   ],
   "rev": [
    2030.2,
    2151.0,
    2278.6
   ],
   "n_est": [
    15,
    15,
    13
   ],
   "pe": [
    18.6,
    17.1,
    15.8
   ],
   "eps_cagr": 8.6,
   "rev_cagr": 5.9
  },
  {
   "id": "TW",
   "ticker": "TW US",
   "name": "Tradeweb Markets Inc.",
   "sector": "Exchanges",
   "price": 101.19,
   "price_ccy": "USD",
   "eps_ccy": "USD",
   "fx": null,
   "eps_src": "Normalized",
   "offcycle": false,
   "price_eps_ccy": 101.19,
   "fy_labels": [
    2026,
    2027,
    2028
   ],
   "eps": [
    4.05,
    4.57,
    5.17
   ],
   "rev": [
    2351.6,
    2604.3,
    2853.5
   ],
   "n_est": [
    14,
    14,
    7
   ],
   "pe": [
    25.0,
    22.2,
    19.6
   ],
   "eps_cagr": 12.9,
   "rev_cagr": 10.2
  },
  {
   "id": "MKTX",
   "ticker": "MKTX US",
   "name": "MarketAxess Holdings Inc.",
   "sector": "Exchanges",
   "price": 120.89,
   "price_ccy": "USD",
   "eps_ccy": "USD",
   "fx": null,
   "eps_src": "Normalized",
   "offcycle": false,
   "price_eps_ccy": 120.89,
   "fy_labels": [
    2026,
    2027,
    2028
   ],
   "eps": [
    8.12,
    8.92,
    10.06
   ],
   "rev": [
    901.3,
    965.1,
    1041.0
   ],
   "n_est": [
    12,
    12,
    7
   ],
   "pe": [
    14.9,
    13.6,
    12.0
   ],
   "eps_cagr": 11.3,
   "rev_cagr": 7.5
  },
  {
   "id": "MIAX",
   "ticker": "MIAX US",
   "name": "Miami International Holdings, Inc.",
   "sector": "Exchanges",
   "price": 43.29,
   "price_ccy": "USD",
   "eps_ccy": "USD",
   "fx": null,
   "eps_src": "Normalized",
   "offcycle": false,
   "price_eps_ccy": 43.29,
   "fy_labels": [
    2026,
    2027,
    2028
   ],
   "eps": [
    1.55,
    1.82,
    1.89
   ],
   "rev": [
    527.5,
    588.5,
    604.8
   ],
   "n_est": [
    6,
    7,
    3
   ],
   "pe": [
    28.0,
    23.8,
    22.9
   ],
   "eps_cagr": 10.5,
   "rev_cagr": 7.1
  },
  {
   "id": "MRX",
   "ticker": "MRX US",
   "name": "Marex Group plc",
   "sector": "Exchanges",
   "price": 61.96,
   "price_ccy": "USD",
   "eps_ccy": "USD",
   "fx": null,
   "eps_src": "Normalized",
   "offcycle": false,
   "price_eps_ccy": 61.96,
   "fy_labels": [
    2026,
    2027,
    2028
   ],
   "eps": [
    5.21,
    5.57,
    6.52
   ],
   "rev": [
    2522.6,
    2648.8,
    2948.5
   ],
   "n_est": [
    7,
    8,
    4
   ],
   "pe": [
    11.9,
    11.1,
    9.5
   ],
   "eps_cagr": 11.8,
   "rev_cagr": 8.1
  },
  {
   "id": "SPGI",
   "ticker": "SPGI US",
   "name": "S&P Global Inc.",
   "sector": "Info Services",
   "price": 418.91,
   "price_ccy": "USD",
   "eps_ccy": "USD",
   "fx": null,
   "eps_src": "Normalized",
   "offcycle": false,
   "price_eps_ccy": 418.91,
   "fy_labels": [
    2026,
    2027,
    2028
   ],
   "eps": [
    19.62,
    22.2,
    25.39
   ],
   "rev": [
    16514.3,
    17701.7,
    18994.2
   ],
   "n_est": [
    24,
    24,
    14
   ],
   "pe": [
    21.4,
    18.9,
    16.5
   ],
   "eps_cagr": 13.8,
   "rev_cagr": 7.2
  },
  {
   "id": "MCO",
   "ticker": "MCO US",
   "name": "Moody's Corporation",
   "sector": "Info Services",
   "price": 447.85,
   "price_ccy": "USD",
   "eps_ccy": "USD",
   "fx": null,
   "eps_src": "Normalized",
   "offcycle": false,
   "price_eps_ccy": 447.85,
   "fy_labels": [
    2026,
    2027,
    2028
   ],
   "eps": [
    16.7,
    18.6,
    20.72
   ],
   "rev": [
    8234.4,
    8850.7,
    9533.4
   ],
   "n_est": [
    23,
    23,
    13
   ],
   "pe": [
    26.8,
    24.1,
    21.6
   ],
   "eps_cagr": 11.4,
   "rev_cagr": 7.6
  },
  {
   "id": "MSCI",
   "ticker": "MSCI US",
   "name": "MSCI Inc.",
   "sector": "Info Services",
   "price": 599.12,
   "price_ccy": "USD",
   "eps_ccy": "USD",
   "fx": null,
   "eps_src": "Normalized",
   "offcycle": false,
   "price_eps_ccy": 599.12,
   "fy_labels": [
    2026,
    2027,
    2028
   ],
   "eps": [
    19.66,
    22.51,
    25.62
   ],
   "rev": [
    3488.4,
    3792.2,
    4103.2
   ],
   "n_est": [
    17,
    17,
    11
   ],
   "pe": [
    30.5,
    26.6,
    23.4
   ],
   "eps_cagr": 14.1,
   "rev_cagr": 8.5
  },
  {
   "id": "FDS",
   "ticker": "FDS US",
   "name": "FactSet Research Systems Inc.",
   "sector": "Info Services",
   "price": 241.16,
   "price_ccy": "USD",
   "eps_ccy": "USD",
   "fx": null,
   "eps_src": "Normalized",
   "offcycle": false,
   "price_eps_ccy": 241.16,
   "fy_labels": [
    2026,
    2027,
    2028
   ],
   "eps": [
    17.71,
    19.39,
    21.44
   ],
   "rev": [
    2464.4,
    2603.5,
    2754.6
   ],
   "n_est": [
    18,
    18,
    14
   ],
   "pe": [
    13.6,
    12.4,
    11.2
   ],
   "eps_cagr": 10.0,
   "rev_cagr": 5.7
  },
  {
   "id": "EFX",
   "ticker": "EFX US",
   "name": "Equifax Inc.",
   "sector": "Info Services",
   "price": 163.71,
   "price_ccy": "USD",
   "eps_ccy": "USD",
   "fx": null,
   "eps_src": "Normalized",
   "offcycle": false,
   "price_eps_ccy": 163.71,
   "fy_labels": [
    2026,
    2027,
    2028
   ],
   "eps": [
    8.6,
    10.28,
    12.55
   ],
   "rev": [
    6766.1,
    7383.7,
    8121.2
   ],
   "n_est": [
    24,
    24,
    14
   ],
   "pe": [
    19.0,
    15.9,
    13.0
   ],
   "eps_cagr": 20.8,
   "rev_cagr": 9.6
  },
  {
   "id": "TRU",
   "ticker": "TRU US",
   "name": "TransUnion",
   "sector": "Info Services",
   "price": 66.13,
   "price_ccy": "USD",
   "eps_ccy": "USD",
   "fx": null,
   "eps_src": "Normalized",
   "offcycle": false,
   "price_eps_ccy": 66.13,
   "fy_labels": [
    2026,
    2027,
    2028
   ],
   "eps": [
    4.78,
    5.58,
    6.57
   ],
   "rev": [
    5133.2,
    5537.2,
    5973.6
   ],
   "n_est": [
    20,
    20,
    12
   ],
   "pe": [
    13.8,
    11.9,
    10.1
   ],
   "eps_cagr": 17.3,
   "rev_cagr": 7.9
  },
  {
   "id": "LSE:EXPN",
   "ticker": "EXPN LN",
   "name": "Experian plc",
   "sector": "Info Services",
   "price": 25.69,
   "price_ccy": "GBP",
   "eps_ccy": "USD",
   "fx": 1.3368,
   "eps_src": "Normalized",
   "offcycle": true,
   "price_eps_ccy": 34.34,
   "fy_labels": [
    2027,
    2028,
    2029
   ],
   "eps": [
    2.02,
    2.27,
    2.57
   ],
   "rev": [
    9193.1,
    9951.4,
    10652.9
   ],
   "n_est": [
    17,
    15,
    12
   ],
   "pe": [
    17.0,
    15.1,
    13.4
   ],
   "eps_cagr": 12.8,
   "rev_cagr": 7.6
  },
  {
   "id": "FICO",
   "ticker": "FICO US",
   "name": "Fair Isaac Corporation",
   "sector": "Info Services",
   "price": 1179.19,
   "price_ccy": "USD",
   "eps_ccy": "USD",
   "fx": null,
   "eps_src": "Normalized",
   "offcycle": false,
   "price_eps_ccy": 1179.19,
   "fy_labels": [
    2026,
    2027,
    2028
   ],
   "eps": [
    43.07,
    54.43,
    65.9
   ],
   "rev": [
    2547.4,
    2934.2,
    3350.4
   ],
   "n_est": [
    21,
    21,
    14
   ],
   "pe": [
    27.4,
    21.7,
    17.9
   ],
   "eps_cagr": 23.7,
   "rev_cagr": 14.7
  },
  {
   "id": "VRSK",
   "ticker": "VRSK US",
   "name": "Verisk Analytics, Inc.",
   "sector": "Info Services",
   "price": 183.8,
   "price_ccy": "USD",
   "eps_ccy": "USD",
   "fx": null,
   "eps_src": "Normalized",
   "offcycle": false,
   "price_eps_ccy": 183.8,
   "fy_labels": [
    2026,
    2027,
    2028
   ],
   "eps": [
    7.65,
    8.66,
    9.66
   ],
   "rev": [
    3219.9,
    3437.3,
    3659.7
   ],
   "n_est": [
    18,
    18,
    10
   ],
   "pe": [
    24.0,
    21.2,
    19.0
   ],
   "eps_cagr": 12.4,
   "rev_cagr": 6.6
  },
  {
   "id": "V",
   "ticker": "V US",
   "name": "Visa Inc.",
   "sector": "Payments / Fintech",
   "price": 322.39,
   "price_ccy": "USD",
   "eps_ccy": "USD",
   "fx": null,
   "eps_src": "Normalized",
   "offcycle": false,
   "price_eps_ccy": 322.39,
   "fy_labels": [
    2026,
    2027,
    2028
   ],
   "eps": [
    13.14,
    14.86,
    16.82
   ],
   "rev": [
    45568.1,
    50339.4,
    55477.9
   ],
   "n_est": [
    37,
    39,
    25
   ],
   "pe": [
    24.5,
    21.7,
    19.2
   ],
   "eps_cagr": 13.1,
   "rev_cagr": 10.3
  },
  {
   "id": "MA",
   "ticker": "MA US",
   "name": "Mastercard Incorporated",
   "sector": "Payments / Fintech",
   "price": 489.98,
   "price_ccy": "USD",
   "eps_ccy": "USD",
   "fx": null,
   "eps_src": "Normalized",
   "offcycle": false,
   "price_eps_ccy": 489.98,
   "fy_labels": [
    2026,
    2027,
    2028
   ],
   "eps": [
    19.66,
    22.78,
    26.46
   ],
   "rev": [
    37084.9,
    41729.0,
    46798.1
   ],
   "n_est": [
    37,
    37,
    20
   ],
   "pe": [
    24.9,
    21.5,
    18.5
   ],
   "eps_cagr": 16.0,
   "rev_cagr": 12.3
  },
  {
   "id": "PYPL",
   "ticker": "PYPL US",
   "name": "PayPal Holdings, Inc.",
   "sector": "Payments / Fintech",
   "price": 41.53,
   "price_ccy": "USD",
   "eps_ccy": "USD",
   "fx": null,
   "eps_src": "Normalized",
   "offcycle": false,
   "price_eps_ccy": 41.53,
   "fy_labels": [
    2026,
    2027,
    2028
   ],
   "eps": [
    5.31,
    5.76,
    6.27
   ],
   "rev": [
    34330.7,
    35789.5,
    37396.4
   ],
   "n_est": [
    41,
    41,
    23
   ],
   "pe": [
    7.8,
    7.2,
    6.6
   ],
   "eps_cagr": 8.7,
   "rev_cagr": 4.4
  },
  {
   "id": "XYZ",
   "ticker": "XYZ US",
   "name": "Block, Inc.",
   "sector": "Payments / Fintech",
   "price": 69.52,
   "price_ccy": "USD",
   "eps_ccy": "USD",
   "fx": null,
   "eps_src": "Normalized",
   "offcycle": false,
   "price_eps_ccy": 69.52,
   "fy_labels": [
    2026,
    2027,
    2028
   ],
   "eps": [
    3.9,
    4.98,
    6.16
   ],
   "rev": [
    26224.4,
    29299.6,
    32898.5
   ],
   "n_est": [
    38,
    40,
    20
   ],
   "pe": [
    17.8,
    14.0,
    11.3
   ],
   "eps_cagr": 25.7,
   "rev_cagr": 12.0
  },
  {
   "id": "ENXTAM:ADYEN",
   "ticker": "ADYEN NA",
   "name": "Adyen N.V.",
   "sector": "Payments / Fintech",
   "price": 828.4,
   "price_ccy": "EUR",
   "eps_ccy": "USD",
   "fx": 1.1537,
   "eps_src": "Normalized",
   "offcycle": false,
   "price_eps_ccy": 955.73,
   "fy_labels": [
    2026,
    2027,
    2028
   ],
   "eps": [
    38.7,
    47.25,
    57.97
   ],
   "rev": [
    2826.5,
    3417.1,
    4107.2
   ],
   "n_est": [
    3,
    2,
    1
   ],
   "pe": [
    24.7,
    20.2,
    16.5
   ],
   "eps_cagr": 22.4,
   "rev_cagr": 20.5
  },
  {
   "id": "TOST",
   "ticker": "TOST US",
   "name": "Toast, Inc.",
   "sector": "Payments / Fintech",
   "price": 24.82,
   "price_ccy": "USD",
   "eps_ccy": "USD",
   "fx": null,
   "eps_src": "Normalized",
   "offcycle": false,
   "price_eps_ccy": 24.82,
   "fy_labels": [
    2026,
    2027,
    2028
   ],
   "eps": [
    1.34,
    1.7,
    2.2
   ],
   "rev": [
    7386.1,
    8721.3,
    10184.6
   ],
   "n_est": [
    15,
    15,
    7
   ],
   "pe": [
    18.5,
    14.6,
    11.3
   ],
   "eps_cagr": 27.9,
   "rev_cagr": 17.4
  },
  {
   "id": "SHOP",
   "ticker": "SHOP US",
   "name": "Shopify Inc.",
   "sector": "Payments / Fintech",
   "price": 108.24,
   "price_ccy": "USD",
   "eps_ccy": "USD",
   "fx": null,
   "eps_src": "Normalized",
   "offcycle": false,
   "price_eps_ccy": 108.24,
   "fy_labels": [
    2026,
    2027,
    2028
   ],
   "eps": [
    1.84,
    2.33,
    3.26
   ],
   "rev": [
    14797.8,
    18323.4,
    23017.4
   ],
   "n_est": [
    40,
    38,
    17
   ],
   "pe": [
    58.9,
    46.4,
    33.2
   ],
   "eps_cagr": 33.3,
   "rev_cagr": 24.7
  },
  {
   "id": "SOFI",
   "ticker": "SOFI US",
   "name": "SoFi Technologies, Inc.",
   "sector": "Payments / Fintech",
   "price": 16.58,
   "price_ccy": "USD",
   "eps_ccy": "USD",
   "fx": null,
   "eps_src": "Normalized",
   "offcycle": false,
   "price_eps_ccy": 16.58,
   "fy_labels": [
    2026,
    2027,
    2028
   ],
   "eps": [
    0.58,
    0.78,
    0.99
   ],
   "rev": [
    4671.2,
    5700.8,
    6907.6
   ],
   "n_est": [
    9,
    8,
    4
   ],
   "pe": [
    28.6,
    21.2,
    16.7
   ],
   "eps_cagr": 30.7,
   "rev_cagr": 21.6
  },
  {
   "id": "FISV",
   "ticker": "FISV US",
   "name": "Fiserv, Inc.",
   "sector": "Payments / Fintech",
   "price": 53.78,
   "price_ccy": "USD",
   "eps_ccy": "USD",
   "fx": null,
   "eps_src": "Normalized",
   "offcycle": false,
   "price_eps_ccy": 53.78,
   "fy_labels": [
    2026,
    2027,
    2028
   ],
   "eps": [
    8.12,
    8.94,
    10.06
   ],
   "rev": [
    20040.1,
    20860.9,
    21642.0
   ],
   "n_est": [
    35,
    35,
    19
   ],
   "pe": [
    6.6,
    6.0,
    5.3
   ],
   "eps_cagr": 11.3,
   "rev_cagr": 3.9
  },
  {
   "id": "FIS",
   "ticker": "FIS US",
   "name": "Fidelity National Information Services, Inc.",
   "sector": "Payments / Fintech",
   "price": 39.2,
   "price_ccy": "USD",
   "eps_ccy": "USD",
   "fx": null,
   "eps_src": "Normalized",
   "offcycle": false,
   "price_eps_ccy": 39.2,
   "fy_labels": [
    2026,
    2027,
    2028
   ],
   "eps": [
    6.27,
    6.85,
    7.48
   ],
   "rev": [
    13797.4,
    14442.4,
    15039.4
   ],
   "n_est": [
    25,
    25,
    11
   ],
   "pe": [
    6.2,
    5.7,
    5.2
   ],
   "eps_cagr": 9.2,
   "rev_cagr": 4.4
  },
  {
   "id": "GPN",
   "ticker": "GPN US",
   "name": "Global Payments Inc.",
   "sector": "Payments / Fintech",
   "price": 67.71,
   "price_ccy": "USD",
   "eps_ccy": "USD",
   "fx": null,
   "eps_src": "Normalized",
   "offcycle": false,
   "price_eps_ccy": 67.71,
   "fy_labels": [
    2026,
    2027,
    2028
   ],
   "eps": [
    13.86,
    16.19,
    18.66
   ],
   "rev": [
    12440.2,
    13138.8,
    13756.8
   ],
   "n_est": [
    32,
    32,
    18
   ],
   "pe": [
    4.9,
    4.2,
    3.6
   ],
   "eps_cagr": 16.1,
   "rev_cagr": 5.2
  },
  {
   "id": "JKHY",
   "ticker": "JKHY US",
   "name": "Jack Henry & Associates, Inc.",
   "sector": "Payments / Fintech",
   "price": 128.23,
   "price_ccy": "USD",
   "eps_ccy": "USD",
   "fx": null,
   "eps_src": "Normalized",
   "offcycle": false,
   "price_eps_ccy": 128.23,
   "fy_labels": [
    2026,
    2027,
    2028
   ],
   "eps": [
    6.55,
    7.09,
    7.66
   ],
   "rev": [
    2529.0,
    2680.6,
    2860.6
   ],
   "n_est": [
    7,
    9,
    7
   ],
   "pe": [
    19.6,
    18.1,
    16.7
   ],
   "eps_cagr": 8.2,
   "rev_cagr": 6.4
  },
  {
   "id": "CPAY",
   "ticker": "CPAY US",
   "name": "Corpay, Inc.",
   "sector": "Payments / Fintech",
   "price": 356.11,
   "price_ccy": "USD",
   "eps_ccy": "USD",
   "fx": null,
   "eps_src": "Normalized",
   "offcycle": false,
   "price_eps_ccy": 356.11,
   "fy_labels": [
    2026,
    2027,
    2028
   ],
   "eps": [
    26.77,
    30.61,
    35.46
   ],
   "rev": [
    5303.2,
    5823.4,
    6336.4
   ],
   "n_est": [
    15,
    15,
    5
   ],
   "pe": [
    13.3,
    11.6,
    10.0
   ],
   "eps_cagr": 15.1,
   "rev_cagr": 9.3
  },
  {
   "id": "WEX",
   "ticker": "WEX US",
   "name": "WEX Inc.",
   "sector": "Payments / Fintech",
   "price": 135.5,
   "price_ccy": "USD",
   "eps_ccy": "USD",
   "fx": null,
   "eps_src": "Normalized",
   "offcycle": false,
   "price_eps_ccy": 135.5,
   "fy_labels": [
    2026,
    2027,
    2028
   ],
   "eps": [
    19.3,
    20.31,
    21.99
   ],
   "rev": [
    2848.6,
    2916.6,
    3028.7
   ],
   "n_est": [
    14,
    14,
    6
   ],
   "pe": [
    7.0,
    6.7,
    6.2
   ],
   "eps_cagr": 6.8,
   "rev_cagr": 3.1
  },
  {
   "id": "AFRM",
   "ticker": "AFRM US",
   "name": "Affirm Holdings, Inc.",
   "sector": "Payments / Fintech",
   "price": 66.17,
   "price_ccy": "USD",
   "eps_ccy": "USD",
   "fx": null,
   "eps_src": "Normalized",
   "offcycle": false,
   "price_eps_ccy": 66.17,
   "fy_labels": [
    2026,
    2027,
    2028
   ],
   "eps": [
    3.1,
    3.78,
    4.73
   ],
   "rev": [
    4202.8,
    4928.3,
    6550.6
   ],
   "n_est": [
    8,
    8,
    8
   ],
   "pe": [
    21.3,
    17.5,
    14.0
   ],
   "eps_cagr": 23.5,
   "rev_cagr": 24.8
  },
  {
   "id": "KLAR",
   "ticker": "KLAR US",
   "name": "Klarna Group plc",
   "sector": "Payments / Fintech",
   "price": 16.23,
   "price_ccy": "USD",
   "eps_ccy": "USD",
   "fx": null,
   "eps_src": "Normalized",
   "offcycle": false,
   "price_eps_ccy": 16.23,
   "fy_labels": [
    2026,
    2027,
    2028
   ],
   "eps": [
    0.23,
    0.98,
    1.49
   ],
   "rev": [
    4430.0,
    5309.9,
    6286.1
   ],
   "n_est": [
    8,
    9,
    7
   ],
   "pe": [
    70.6,
    16.6,
    10.9
   ],
   "eps_cagr": 154.8,
   "rev_cagr": 19.1
  },
  {
   "id": "BILL",
   "ticker": "BILL US",
   "name": "BILL Holdings, Inc.",
   "sector": "Payments / Fintech",
   "price": 33.18,
   "price_ccy": "USD",
   "eps_ccy": "USD",
   "fx": null,
   "eps_src": "Normalized",
   "offcycle": false,
   "price_eps_ccy": 33.18,
   "fy_labels": [
    2026,
    2027,
    2028
   ],
   "eps": [
    2.64,
    3.34,
    4.06
   ],
   "rev": [
    1645.5,
    1853.1,
    2103.5
   ],
   "n_est": [
    21,
    21,
    11
   ],
   "pe": [
    12.6,
    9.9,
    8.2
   ],
   "eps_cagr": 24.0,
   "rev_cagr": 13.1
  },
  {
   "id": "CHYM",
   "ticker": "CHYM US",
   "name": "Chime Financial, Inc.",
   "sector": "Payments / Fintech",
   "price": 16.7,
   "price_ccy": "USD",
   "eps_ccy": "USD",
   "fx": null,
   "eps_src": "GAAP",
   "offcycle": false,
   "price_eps_ccy": 16.7,
   "fy_labels": [
    2026,
    2027,
    2028
   ],
   "eps": [
    0.32,
    0.78,
    1.04
   ],
   "rev": [
    2679.7,
    3194.5,
    3728.7
   ],
   "n_est": [
    14,
    15,
    7
   ],
   "pe": [
    52.2,
    21.5,
    16.0
   ],
   "eps_cagr": 80.5,
   "rev_cagr": 18.0
  },
  {
   "id": "MQ",
   "ticker": "MQ US",
   "name": "Marqeta, Inc.",
   "sector": "Payments / Fintech",
   "price": 3.83,
   "price_ccy": "USD",
   "eps_ccy": "USD",
   "fx": null,
   "eps_src": "Normalized",
   "offcycle": false,
   "price_eps_ccy": 3.83,
   "fy_labels": [
    2026,
    2027,
    2028
   ],
   "eps": [
    0.03,
    0.11,
    0.11
   ],
   "rev": [
    708.8,
    828.1,
    950.8
   ],
   "n_est": [
    2,
    3,
    1
   ],
   "pe": [
    140.2,
    36.5,
    34.8
   ],
   "eps_cagr": 100.7,
   "rev_cagr": 15.8
  },
  {
   "id": "FOUR",
   "ticker": "FOUR US",
   "name": "Shift4 Payments, Inc.",
   "sector": "Payments / Fintech",
   "price": 41.18,
   "price_ccy": "USD",
   "eps_ccy": "USD",
   "fx": null,
   "eps_src": "Normalized",
   "offcycle": false,
   "price_eps_ccy": 41.18,
   "fy_labels": [
    2026,
    2027,
    2028
   ],
   "eps": [
    5.59,
    6.76,
    7.87
   ],
   "rev": [
    5096.5,
    5797.3,
    6515.5
   ],
   "n_est": [
    23,
    22,
    9
   ],
   "pe": [
    7.4,
    6.1,
    5.2
   ],
   "eps_cagr": 18.6,
   "rev_cagr": 13.1
  },
  {
   "id": "LSE:WISE",
   "ticker": "WISE LN",
   "name": "Wise Group plc",
   "sector": "Payments / Fintech",
   "price": 8.04,
   "price_ccy": "GBP",
   "eps_ccy": "GBP",
   "fx": null,
   "eps_src": "Normalized",
   "offcycle": false,
   "price_eps_ccy": 8.04,
   "fy_labels": [
    2026,
    2027,
    2028
   ],
   "eps": [
    0.37,
    0.57,
    0.68
   ],
   "rev": [
    1869.3,
    2170.7,
    2530.0
   ],
   "n_est": [
    19,
    19,
    3
   ],
   "pe": [
    22.0,
    14.1,
    11.8
   ],
   "eps_cagr": 36.2,
   "rev_cagr": 16.3
  },
  {
   "id": "RELY",
   "ticker": "RELY LN",
   "name": "Remitly Global, Inc.",
   "sector": "Payments / Fintech",
   "price": 19.08,
   "price_ccy": "USD",
   "eps_ccy": "USD",
   "fx": null,
   "eps_src": "Normalized",
   "offcycle": false,
   "price_eps_ccy": 19.08,
   "fy_labels": [
    2026,
    2027,
    2028
   ],
   "eps": [
    1.37,
    1.65,
    1.98
   ],
   "rev": [
    1972.0,
    2348.5,
    2764.4
   ],
   "n_est": [
    3,
    3,
    3
   ],
   "pe": [
    14.0,
    11.6,
    9.6
   ],
   "eps_cagr": 20.3,
   "rev_cagr": 18.4
  },
  {
   "id": "WU",
   "ticker": "WU US",
   "name": "The Western Union Company",
   "sector": "Payments / Fintech",
   "price": 7.55,
   "price_ccy": "USD",
   "eps_ccy": "USD",
   "fx": null,
   "eps_src": "Normalized",
   "offcycle": false,
   "price_eps_ccy": 7.55,
   "fy_labels": [
    2026,
    2027,
    2028
   ],
   "eps": [
    1.75,
    1.92,
    2.06
   ],
   "rev": [
    4275.1,
    4474.2,
    4641.9
   ],
   "n_est": [
    17,
    17,
    9
   ],
   "pe": [
    4.3,
    3.9,
    3.7
   ],
   "eps_cagr": 8.4,
   "rev_cagr": 4.2
  },
  {
   "id": "LAZ",
   "ticker": "LAZ US",
   "name": "Lazard, Inc.",
   "sector": "M&A Boutiques",
   "price": 43.72,
   "price_ccy": "USD",
   "eps_ccy": "USD",
   "fx": null,
   "eps_src": "Normalized",
   "offcycle": false,
   "price_eps_ccy": 43.72,
   "fy_labels": [
    2026,
    2027,
    2028
   ],
   "eps": [
    2.85,
    4.39,
    5.62
   ],
   "rev": [
    3381.9,
    4007.4,
    4388.6
   ],
   "n_est": [
    9,
    10,
    3
   ],
   "pe": [
    15.3,
    10.0,
    7.8
   ],
   "eps_cagr": 40.5,
   "rev_cagr": 13.9
  },
  {
   "id": "EVR",
   "ticker": "EVR US",
   "name": "Evercore Inc.",
   "sector": "M&A Boutiques",
   "price": 357.38,
   "price_ccy": "USD",
   "eps_ccy": "USD",
   "fx": null,
   "eps_src": "Normalized",
   "offcycle": false,
   "price_eps_ccy": 357.38,
   "fy_labels": [
    2026,
    2027,
    2028
   ],
   "eps": [
    19.22,
    23.01,
    27.05
   ],
   "rev": [
    4706.1,
    5365.9,
    5412.4
   ],
   "n_est": [
    10,
    10,
    3
   ],
   "pe": [
    18.6,
    15.5,
    13.2
   ],
   "eps_cagr": 18.7,
   "rev_cagr": 7.2
  },
  {
   "id": "MC",
   "ticker": "MC US",
   "name": "Moelis & Company",
   "sector": "M&A Boutiques",
   "price": 67.7,
   "price_ccy": "USD",
   "eps_ccy": "USD",
   "fx": null,
   "eps_src": "Normalized",
   "offcycle": false,
   "price_eps_ccy": 67.7,
   "fy_labels": [
    2026,
    2027,
    2028
   ],
   "eps": [
    3.09,
    4.09,
    4.41
   ],
   "rev": [
    1692.0,
    1992.7,
    2201.1
   ],
   "n_est": [
    11,
    11,
    3
   ],
   "pe": [
    21.9,
    16.5,
    15.4
   ],
   "eps_cagr": 19.3,
   "rev_cagr": 14.1
  },
  {
   "id": "HLI",
   "ticker": "HLI US",
   "name": "Houlihan Lokey, Inc.",
   "sector": "M&A Boutiques",
   "price": 137.89,
   "price_ccy": "USD",
   "eps_ccy": "USD",
   "fx": null,
   "eps_src": "Normalized",
   "offcycle": true,
   "price_eps_ccy": 137.89,
   "fy_labels": [
    2027,
    2028,
    2029
   ],
   "eps": [
    8.21,
    9.44,
    10.73
   ],
   "rev": [
    2946.2,
    3336.1,
    3581.5
   ],
   "n_est": [
    10,
    9,
    3
   ],
   "pe": [
    16.8,
    14.6,
    12.8
   ],
   "eps_cagr": 14.3,
   "rev_cagr": 10.3
  },
  {
   "id": "PWP",
   "ticker": "PWP US",
   "name": "Perella Weinberg Partners",
   "sector": "M&A Boutiques",
   "price": 15.66,
   "price_ccy": "USD",
   "eps_ccy": "USD",
   "fx": null,
   "eps_src": "Normalized",
   "offcycle": false,
   "price_eps_ccy": 15.66,
   "fy_labels": [
    2026,
    2027,
    2028
   ],
   "eps": [
    1.01,
    1.5,
    1.79
   ],
   "rev": [
    883.6,
    1098.4,
    1184.8
   ],
   "n_est": [
    4,
    4,
    1
   ],
   "pe": [
    15.5,
    10.4,
    8.7
   ],
   "eps_cagr": 33.1,
   "rev_cagr": 15.8
  },
  {
   "id": "PJT",
   "ticker": "PJT US",
   "name": "PJT Partners Inc.",
   "sector": "M&A Boutiques",
   "price": 152.37,
   "price_ccy": "USD",
   "eps_ccy": "USD",
   "fx": null,
   "eps_src": "Normalized",
   "offcycle": false,
   "price_eps_ccy": 152.37,
   "fy_labels": [
    2026,
    2027,
    2028
   ],
   "eps": [
    7.52,
    8.55,
    9.57
   ],
   "rev": [
    1871.6,
    2067.7,
    2174.9
   ],
   "n_est": [
    7,
    7,
    2
   ],
   "pe": [
    20.3,
    17.8,
    15.9
   ],
   "eps_cagr": 12.8,
   "rev_cagr": 7.8
  },
  {
   "id": "PIPR",
   "ticker": "PIPR US",
   "name": "Piper Sandler Companies",
   "sector": "M&A Boutiques",
   "price": 79.05,
   "price_ccy": "USD",
   "eps_ccy": "USD",
   "fx": null,
   "eps_src": "Normalized",
   "offcycle": false,
   "price_eps_ccy": 79.05,
   "fy_labels": [
    2026,
    2027,
    2028
   ],
   "eps": [
    4.71,
    5.62,
    6.31
   ],
   "rev": [
    2067.2,
    2315.6,
    2486.7
   ],
   "n_est": [
    5,
    5,
    1
   ],
   "pe": [
    16.8,
    14.1,
    12.5
   ],
   "eps_cagr": 15.7,
   "rev_cagr": 9.7
  },
  {
   "id": "SWX:PGHN",
   "ticker": "PGHN SW",
   "name": "Partners Group Holding AG",
   "sector": "Alternatives",
   "price": 697.8,
   "price_ccy": "CHF",
   "eps_ccy": "CHF",
   "fx": null,
   "eps_src": "Normalized",
   "offcycle": false,
   "price_eps_ccy": 697.8,
   "fy_labels": [
    2026,
    2027,
    2028
   ],
   "eps": [
    46.78,
    53.66,
    61.04
   ],
   "rev": [
    2538.7,
    2908.5,
    3299.6
   ],
   "n_est": [
    13,
    13,
    11
   ],
   "pe": [
    14.9,
    13.0,
    11.4
   ],
   "eps_cagr": 14.2,
   "rev_cagr": 14.0
  },
  {
   "id": "OM:EQT",
   "ticker": "EQT SS",
   "name": "EQT AB (publ)",
   "sector": "Alternatives",
   "price": 287.5,
   "price_ccy": "SEK",
   "eps_ccy": "EUR",
   "fx": 0.0916,
   "eps_src": "Normalized",
   "offcycle": false,
   "price_eps_ccy": 26.33,
   "fy_labels": [
    2026,
    2027,
    2028
   ],
   "eps": [
    1.22,
    1.68,
    1.98
   ],
   "rev": [
    2870.2,
    3840.5,
    4277.5
   ],
   "n_est": [
    9,
    8,
    7
   ],
   "pe": [
    21.6,
    15.7,
    13.3
   ],
   "eps_cagr": 27.5,
   "rev_cagr": 22.1
  },
  {
   "id": "ENXTAM:CVC",
   "ticker": "CVC NA",
   "name": "CVC Capital Partners plc",
   "sector": "Alternatives",
   "price": 12.95,
   "price_ccy": "EUR",
   "eps_ccy": "EUR",
   "fx": null,
   "eps_src": "Normalized",
   "offcycle": false,
   "price_eps_ccy": 12.95,
   "fy_labels": [
    2026,
    2027,
    2028
   ],
   "eps": [
    0.85,
    0.97,
    1.32
   ],
   "rev": [
    1884.3,
    2107.2,
    2573.8
   ],
   "n_est": [
    9,
    9,
    7
   ],
   "pe": [
    15.3,
    13.4,
    9.8
   ],
   "eps_cagr": 25.1,
   "rev_cagr": 16.9
  },
  {
   "id": "LSE:ICG",
   "ticker": "ICG LN",
   "name": "ICG plc",
   "sector": "Alternatives",
   "price": 17.79,
   "price_ccy": "GBP",
   "eps_ccy": "GBP",
   "fx": null,
   "eps_src": "Normalized",
   "offcycle": true,
   "price_eps_ccy": 17.79,
   "fy_labels": [
    2027,
    2028,
    2029
   ],
   "eps": [
    1.77,
    1.95,
    2.18
   ],
   "rev": [
    1058.7,
    1155.6,
    1256.4
   ],
   "n_est": [
    10,
    11,
    5
   ],
   "pe": [
    10.1,
    9.1,
    8.2
   ],
   "eps_cagr": 11.1,
   "rev_cagr": 8.9
  },
  {
   "id": "ARES",
   "ticker": "ARES US",
   "name": "Ares Management Corporation",
   "sector": "Alternatives",
   "price": 134.9,
   "price_ccy": "USD",
   "eps_ccy": "USD",
   "fx": null,
   "eps_src": "Normalized",
   "offcycle": false,
   "price_eps_ccy": 134.9,
   "fy_labels": [
    2026,
    2027,
    2028
   ],
   "eps": [
    5.94,
    7.32,
    8.46
   ],
   "rev": [
    4921.0,
    6105.8,
    7159.2
   ],
   "n_est": [
    12,
    14,
    6
   ],
   "pe": [
    22.7,
    18.4,
    15.9
   ],
   "eps_cagr": 19.3,
   "rev_cagr": 20.6
  },
  {
   "id": "APO",
   "ticker": "APO US",
   "name": "Apollo Global Management, Inc.",
   "sector": "Alternatives",
   "price": 133.88,
   "price_ccy": "USD",
   "eps_ccy": "USD",
   "fx": null,
   "eps_src": "Normalized",
   "offcycle": false,
   "price_eps_ccy": 133.88,
   "fy_labels": [
    2026,
    2027,
    2028
   ],
   "eps": [
    8.88,
    10.61,
    12.48
   ],
   "rev": [
    5483.5,
    6279.2,
    null
   ],
   "n_est": [
    18,
    18,
    6
   ],
   "pe": [
    15.1,
    12.6,
    10.7
   ],
   "eps_cagr": 18.5,
   "rev_cagr": null
  },
  {
   "id": "BX",
   "ticker": "BX US",
   "name": "Blackstone Inc.",
   "sector": "Alternatives",
   "price": 122.79,
   "price_ccy": "USD",
   "eps_ccy": "USD",
   "fx": null,
   "eps_src": "Normalized",
   "offcycle": false,
   "price_eps_ccy": 122.79,
   "fy_labels": [
    2026,
    2027,
    2028
   ],
   "eps": [
    5.94,
    7.54,
    8.07
   ],
   "rev": [
    14962.9,
    18935.5,
    21342.8
   ],
   "n_est": [
    19,
    19,
    6
   ],
   "pe": [
    20.7,
    16.3,
    15.2
   ],
   "eps_cagr": 16.6,
   "rev_cagr": 19.4
  },
  {
   "id": "KKR",
   "ticker": "KKR US",
   "name": "KKR & Co. Inc.",
   "sector": "Alternatives",
   "price": 96.24,
   "price_ccy": "USD",
   "eps_ccy": "USD",
   "fx": null,
   "eps_src": "Normalized",
   "offcycle": false,
   "price_eps_ccy": 96.24,
   "fy_labels": [
    2026,
    2027,
    2028
   ],
   "eps": [
    6.04,
    7.4,
    8.59
   ],
   "rev": [
    10340.0,
    12218.3,
    13699.3
   ],
   "n_est": [
    20,
    20,
    8
   ],
   "pe": [
    15.9,
    13.0,
    11.2
   ],
   "eps_cagr": 19.3,
   "rev_cagr": 15.1
  },
  {
   "id": "OWL",
   "ticker": "OWL US",
   "name": "Blue Owl Capital Inc.",
   "sector": "Alternatives",
   "price": 9.68,
   "price_ccy": "USD",
   "eps_ccy": "USD",
   "fx": null,
   "eps_src": "Normalized",
   "offcycle": false,
   "price_eps_ccy": 9.68,
   "fy_labels": [
    2026,
    2027,
    2028
   ],
   "eps": [
    0.88,
    0.98,
    1.16
   ],
   "rev": [
    2890.8,
    3213.7,
    3574.9
   ],
   "n_est": [
    14,
    15,
    5
   ],
   "pe": [
    11.0,
    9.9,
    8.3
   ],
   "eps_cagr": 14.5,
   "rev_cagr": 11.2
  },
  {
   "id": "CG",
   "ticker": "CG US",
   "name": "The Carlyle Group Inc.",
   "sector": "Alternatives",
   "price": 45.75,
   "price_ccy": "USD",
   "eps_ccy": "USD",
   "fx": null,
   "eps_src": "Normalized",
   "offcycle": false,
   "price_eps_ccy": 45.75,
   "fy_labels": [
    2026,
    2027,
    2028
   ],
   "eps": [
    4.09,
    5.22,
    5.67
   ],
   "rev": [
    3791.1,
    5043.0,
    5597.6
   ],
   "n_est": [
    14,
    13,
    3
   ],
   "pe": [
    11.2,
    8.8,
    8.1
   ],
   "eps_cagr": 17.8,
   "rev_cagr": 21.5
  },
  {
   "id": "BAM",
   "ticker": "BAM US",
   "name": "Brookfield Asset Management Ltd.",
   "sector": "Alternatives",
   "price": 47.13,
   "price_ccy": "USD",
   "eps_ccy": "USD",
   "fx": null,
   "eps_src": "Normalized",
   "offcycle": false,
   "price_eps_ccy": 47.13,
   "fy_labels": [
    2026,
    2027,
    2028
   ],
   "eps": [
    1.84,
    2.18,
    2.57
   ],
   "rev": [
    6020.4,
    7000.1,
    7944.4
   ],
   "n_est": [
    17,
    17,
    6
   ],
   "pe": [
    25.6,
    21.6,
    18.3
   ],
   "eps_cagr": 18.3,
   "rev_cagr": 14.9
  },
  {
   "id": "TPG",
   "ticker": "TPG US",
   "name": "TPG Inc.",
   "sector": "Alternatives",
   "price": 43.01,
   "price_ccy": "USD",
   "eps_ccy": "USD",
   "fx": null,
   "eps_src": "Normalized",
   "offcycle": false,
   "price_eps_ccy": 43.01,
   "fy_labels": [
    2026,
    2027,
    2028
   ],
   "eps": [
    2.83,
    3.56,
    4.17
   ],
   "rev": [
    2473.7,
    2992.3,
    null
   ],
   "n_est": [
    13,
    13,
    3
   ],
   "pe": [
    15.2,
    12.1,
    10.3
   ],
   "eps_cagr": 21.3,
   "rev_cagr": null
  },
  {
   "id": "STEP",
   "ticker": "STEP US",
   "name": "StepStone Group Inc.",
   "sector": "Alternatives",
   "price": 44.39,
   "price_ccy": "USD",
   "eps_ccy": "USD",
   "fx": null,
   "eps_src": "Normalized",
   "offcycle": true,
   "price_eps_ccy": 44.39,
   "fy_labels": [
    2027,
    2028,
    2029
   ],
   "eps": [
    2.5,
    3.31,
    3.48
   ],
   "rev": [
    1557.9,
    1774.2,
    1768.3
   ],
   "n_est": [
    8,
    7,
    1
   ],
   "pe": [
    17.8,
    13.4,
    12.8
   ],
   "eps_cagr": 18.0,
   "rev_cagr": 6.5
  },
  {
   "id": "HLNE",
   "ticker": "HLNE US",
   "name": "Hamilton Lane Incorporated",
   "sector": "Alternatives",
   "price": 80.1,
   "price_ccy": "USD",
   "eps_ccy": "USD",
   "fx": null,
   "eps_src": "Normalized",
   "offcycle": true,
   "price_eps_ccy": 80.1,
   "fy_labels": [
    2027,
    2028,
    2029
   ],
   "eps": [
    6.1,
    7.4,
    8.17
   ],
   "rev": [
    886.4,
    1050.9,
    1144.4
   ],
   "n_est": [
    7,
    5,
    1
   ],
   "pe": [
    13.1,
    10.8,
    9.8
   ],
   "eps_cagr": 15.7,
   "rev_cagr": 13.6
  },
  {
   "id": "BLK",
   "ticker": "BLK US",
   "name": "BlackRock, Inc.",
   "sector": "Traditionals",
   "price": 1032.0,
   "price_ccy": "USD",
   "eps_ccy": "USD",
   "fx": null,
   "eps_src": "Normalized",
   "offcycle": false,
   "price_eps_ccy": 1032.0,
   "fy_labels": [
    2026,
    2027,
    2028
   ],
   "eps": [
    53.17,
    60.72,
    70.54
   ],
   "rev": [
    27912.2,
    30842.1,
    34699.1
   ],
   "n_est": [
    15,
    15,
    6
   ],
   "pe": [
    19.4,
    17.0,
    14.6
   ],
   "eps_cagr": 15.2,
   "rev_cagr": 11.5
  },
  {
   "id": "TROW",
   "ticker": "TROW US",
   "name": "T. Rowe Price Group, Inc.",
   "sector": "Traditionals",
   "price": 109.64,
   "price_ccy": "USD",
   "eps_ccy": "USD",
   "fx": null,
   "eps_src": "Normalized",
   "offcycle": false,
   "price_eps_ccy": 109.64,
   "fy_labels": [
    2026,
    2027,
    2028
   ],
   "eps": [
    9.57,
    9.67,
    9.68
   ],
   "rev": [
    7543.7,
    7661.1,
    7784.4
   ],
   "n_est": [
    13,
    13,
    4
   ],
   "pe": [
    11.5,
    11.3,
    11.3
   ],
   "eps_cagr": 0.6,
   "rev_cagr": 1.6
  },
  {
   "id": "XTRA:DWS",
   "ticker": "DWS GY",
   "name": "DWS Group GmbH & Co. KGaA",
   "sector": "Traditionals",
   "price": 60.8,
   "price_ccy": "EUR",
   "eps_ccy": "EUR",
   "fx": null,
   "eps_src": "Normalized",
   "offcycle": false,
   "price_eps_ccy": 60.8,
   "fy_labels": [
    2026,
    2027,
    2028
   ],
   "eps": [
    5.06,
    5.26,
    5.77
   ],
   "rev": [
    3252.1,
    3325.4,
    3516.6
   ],
   "n_est": [
    7,
    8,
    8
   ],
   "pe": [
    12.0,
    11.6,
    10.5
   ],
   "eps_cagr": 6.9,
   "rev_cagr": 4.0
  },
  {
   "id": "ENXTPA:AMUN",
   "ticker": "AMUN FP",
   "name": "Amundi S.A.",
   "sector": "Traditionals",
   "price": 82.55,
   "price_ccy": "EUR",
   "eps_ccy": "EUR",
   "fx": null,
   "eps_src": "Normalized",
   "offcycle": false,
   "price_eps_ccy": 82.55,
   "fy_labels": [
    2026,
    2027,
    2028
   ],
   "eps": [
    7.17,
    7.59,
    7.82
   ],
   "rev": [
    3486.4,
    3533.6,
    3614.6
   ],
   "n_est": [
    14,
    14,
    13
   ],
   "pe": [
    11.5,
    10.9,
    10.6
   ],
   "eps_cagr": 4.5,
   "rev_cagr": 1.8
  },
  {
   "id": "AB",
   "ticker": "AB US",
   "name": "AllianceBernstein Holding L.P.",
   "sector": "Traditionals",
   "price": 36.44,
   "price_ccy": "USD",
   "eps_ccy": "USD",
   "fx": null,
   "eps_src": "Normalized",
   "offcycle": false,
   "price_eps_ccy": 36.44,
   "fy_labels": [
    2026,
    2027,
    2028
   ],
   "eps": [
    3.47,
    3.83,
    4.22
   ],
   "rev": [
    3698.7,
    3980.1,
    4411.4
   ],
   "n_est": [
    7,
    7,
    2
   ],
   "pe": [
    10.5,
    9.5,
    8.6
   ],
   "eps_cagr": 10.3,
   "rev_cagr": 9.2
  },
  {
   "id": "BEN",
   "ticker": "BEN US",
   "name": "Franklin Resources, Inc.",
   "sector": "Traditionals",
   "price": 32.13,
   "price_ccy": "USD",
   "eps_ccy": "USD",
   "fx": null,
   "eps_src": "Normalized",
   "offcycle": false,
   "price_eps_ccy": 32.13,
   "fy_labels": [
    2026,
    2027,
    2028
   ],
   "eps": [
    2.75,
    2.98,
    3.29
   ],
   "rev": [
    9090.0,
    9180.3,
    8918.6
   ],
   "n_est": [
    10,
    11,
    4
   ],
   "pe": [
    11.7,
    10.8,
    9.8
   ],
   "eps_cagr": 9.3,
   "rev_cagr": -0.9
  },
  {
   "id": "IVZ",
   "ticker": "IVZ US",
   "name": "Invesco Ltd.",
   "sector": "Traditionals",
   "price": 28.92,
   "price_ccy": "USD",
   "eps_ccy": "USD",
   "fx": null,
   "eps_src": "Normalized",
   "offcycle": false,
   "price_eps_ccy": 28.92,
   "fy_labels": [
    2026,
    2027,
    2028
   ],
   "eps": [
    2.6,
    2.99,
    3.31
   ],
   "rev": [
    5181.2,
    5495.4,
    null
   ],
   "n_est": [
    12,
    12,
    4
   ],
   "pe": [
    11.1,
    9.7,
    8.7
   ],
   "eps_cagr": 13.0,
   "rev_cagr": null
  },
  {
   "id": "AMP",
   "ticker": "AMP US",
   "name": "Ameriprise Financial, Inc.",
   "sector": "Traditionals",
   "price": 459.13,
   "price_ccy": "USD",
   "eps_ccy": "USD",
   "fx": null,
   "eps_src": "Normalized",
   "offcycle": false,
   "price_eps_ccy": 459.13,
   "fy_labels": [
    2026,
    2027,
    2028
   ],
   "eps": [
    44.17,
    47.64,
    52.85
   ],
   "rev": [
    19287.3,
    20156.3,
    21127.5
   ],
   "n_est": [
    13,
    13,
    4
   ],
   "pe": [
    10.4,
    9.6,
    8.7
   ],
   "eps_cagr": 9.4,
   "rev_cagr": 4.7
  },
  {
   "id": "SCHW",
   "ticker": "SCHW US",
   "name": "The Charles Schwab Corporation",
   "sector": "Wealth / Brokers",
   "price": 91.1,
   "price_ccy": "USD",
   "eps_ccy": "USD",
   "fx": null,
   "eps_src": "Normalized",
   "offcycle": false,
   "price_eps_ccy": 91.1,
   "fy_labels": [
    2026,
    2027,
    2028
   ],
   "eps": [
    6.15,
    7.25,
    8.16
   ],
   "rev": [
    27265.4,
    29570.9,
    31834.4
   ],
   "n_est": [
    20,
    20,
    8
   ],
   "pe": [
    14.8,
    12.6,
    11.2
   ],
   "eps_cagr": 15.1,
   "rev_cagr": 8.1
  },
  {
   "id": "LPLA",
   "ticker": "LPLA US",
   "name": "LPL Financial Holdings Inc.",
   "sector": "Wealth / Brokers",
   "price": 295.66,
   "price_ccy": "USD",
   "eps_ccy": "USD",
   "fx": null,
   "eps_src": "Normalized",
   "offcycle": false,
   "price_eps_ccy": 295.66,
   "fy_labels": [
    2026,
    2027,
    2028
   ],
   "eps": [
    23.2,
    28.45,
    34.19
   ],
   "rev": [
    20575.2,
    23293.6,
    25425.6
   ],
   "n_est": [
    15,
    16,
    7
   ],
   "pe": [
    12.7,
    10.4,
    8.6
   ],
   "eps_cagr": 21.4,
   "rev_cagr": 11.2
  },
  {
   "id": "HOOD",
   "ticker": "HOOD US",
   "name": "Robinhood Markets, Inc.",
   "sector": "Wealth / Brokers",
   "price": 93.19,
   "price_ccy": "USD",
   "eps_ccy": "USD",
   "fx": null,
   "eps_src": "Normalized",
   "offcycle": false,
   "price_eps_ccy": 93.19,
   "fy_labels": [
    2026,
    2027,
    2028
   ],
   "eps": [
    2.17,
    2.8,
    3.56
   ],
   "rev": [
    5000.4,
    6093.9,
    6886.2
   ],
   "n_est": [
    6,
    6,
    4
   ],
   "pe": [
    43.0,
    33.3,
    26.2
   ],
   "eps_cagr": 28.2,
   "rev_cagr": 17.4
  },
  {
   "id": "IBKR",
   "ticker": "IBKR US",
   "name": "Interactive Brokers Group, Inc.",
   "sector": "Wealth / Brokers",
   "price": 90.81,
   "price_ccy": "USD",
   "eps_ccy": "USD",
   "fx": null,
   "eps_src": "Normalized",
   "offcycle": false,
   "price_eps_ccy": 90.81,
   "fy_labels": [
    2026,
    2027,
    2028
   ],
   "eps": [
    2.51,
    2.88,
    3.28
   ],
   "rev": [
    7046.8,
    7927.6,
    9426.6
   ],
   "n_est": [
    10,
    11,
    5
   ],
   "pe": [
    36.1,
    31.6,
    27.7
   ],
   "eps_cagr": 14.3,
   "rev_cagr": 15.7
  },
  {
   "id": "COIN",
   "ticker": "COIN US",
   "name": "Coinbase Global, Inc.",
   "sector": "Wealth / Brokers",
   "price": 159.78,
   "price_ccy": "USD",
   "eps_ccy": "USD",
   "fx": null,
   "eps_src": "Normalized",
   "offcycle": false,
   "price_eps_ccy": 159.78,
   "fy_labels": [
    2026,
    2027,
    2028
   ],
   "eps": [
    1.22,
    4.97,
    6.27
   ],
   "rev": [
    6154.0,
    7761.7,
    8319.9
   ],
   "n_est": [
    16,
    22,
    7
   ],
   "pe": [
    131.0,
    32.2,
    25.5
   ],
   "eps_cagr": 126.7,
   "rev_cagr": 16.3
  },
  {
   "id": "RJF",
   "ticker": "RJF US",
   "name": "Raymond James Financial, Inc.",
   "sector": "Wealth / Brokers",
   "price": 154.4,
   "price_ccy": "USD",
   "eps_ccy": "USD",
   "fx": null,
   "eps_src": "Normalized",
   "offcycle": false,
   "price_eps_ccy": 154.4,
   "fy_labels": [
    2026,
    2027,
    2028
   ],
   "eps": [
    11.86,
    13.37,
    14.34
   ],
   "rev": [
    15561.8,
    16731.3,
    17359.4
   ],
   "n_est": [
    13,
    13,
    4
   ],
   "pe": [
    13.0,
    11.5,
    10.8
   ],
   "eps_cagr": 9.9,
   "rev_cagr": 5.6
  },
  {
   "id": "SF",
   "ticker": "SF US",
   "name": "Stifel Financial Corp.",
   "sector": "Wealth / Brokers",
   "price": 72.66,
   "price_ccy": "USD",
   "eps_ccy": "USD",
   "fx": null,
   "eps_src": "Normalized",
   "offcycle": false,
   "price_eps_ccy": 72.66,
   "fy_labels": [
    2026,
    2027,
    2028
   ],
   "eps": [
    6.31,
    7.0,
    6.72
   ],
   "rev": [
    5996.6,
    6467.2,
    6614.3
   ],
   "n_est": [
    8,
    8,
    3
   ],
   "pe": [
    11.5,
    10.4,
    10.8
   ],
   "eps_cagr": 3.3,
   "rev_cagr": 5.0
  },
  {
   "id": "WLTH",
   "ticker": "WLTH US",
   "name": "Wealthfront Corporation",
   "sector": "Wealth / Brokers",
   "price": 8.96,
   "price_ccy": "USD",
   "eps_ccy": "USD",
   "fx": null,
   "eps_src": "Normalized",
   "offcycle": true,
   "price_eps_ccy": 8.96,
   "fy_labels": [
    2027,
    2028,
    2029
   ],
   "eps": [
    0.68,
    0.8,
    1.0
   ],
   "rev": [
    379.7,
    457.5,
    589.9
   ],
   "n_est": [
    4,
    4,
    1
   ],
   "pe": [
    13.2,
    11.3,
    9.0
   ],
   "eps_cagr": 21.3,
   "rev_cagr": 24.6
  },
  {
   "id": "ETOR",
   "ticker": "ETOR US",
   "name": "eToro Group Ltd.",
   "sector": "Wealth / Brokers",
   "price": 38.52,
   "price_ccy": "USD",
   "eps_ccy": "USD",
   "fx": null,
   "eps_src": "Normalized",
   "offcycle": false,
   "price_eps_ccy": 38.52,
   "fy_labels": [
    2026,
    2027,
    2028
   ],
   "eps": [
    2.81,
    3.25,
    3.77
   ],
   "rev": [
    965.0,
    1058.1,
    1106.9
   ],
   "n_est": [
    12,
    12,
    6
   ],
   "pe": [
    13.7,
    11.9,
    10.2
   ],
   "eps_cagr": 15.8,
   "rev_cagr": 7.1
  },
  {
   "id": "SWX:SQN",
   "ticker": "SQ SW",
   "name": "Swissquote Group Holding SA",
   "sector": "Wealth / Brokers",
   "price": 39.42,
   "price_ccy": "CHF",
   "eps_ccy": "CHF",
   "fx": null,
   "eps_src": "Normalized",
   "offcycle": false,
   "price_eps_ccy": 39.42,
   "fy_labels": [
    2026,
    2027,
    2028
   ],
   "eps": [
    2.22,
    2.51,
    2.87
   ],
   "rev": [
    761.2,
    834.0,
    928.4
   ],
   "n_est": [
    11,
    11,
    7
   ],
   "pe": [
    17.7,
    15.7,
    13.7
   ],
   "eps_cagr": 13.7,
   "rev_cagr": 10.4
  },
  {
   "id": "XTRA:FTK",
   "ticker": "FTK GY",
   "name": "flatexDEGIRO SE",
   "sector": "Wealth / Brokers",
   "price": 36.12,
   "price_ccy": "EUR",
   "eps_ccy": "EUR",
   "fx": null,
   "eps_src": "Normalized",
   "offcycle": false,
   "price_eps_ccy": 36.12,
   "fy_labels": [
    2026,
    2027,
    2028
   ],
   "eps": [
    1.9,
    2.28,
    2.62
   ],
   "rev": [
    626.8,
    700.3,
    783.5
   ],
   "n_est": [
    11,
    11,
    10
   ],
   "pe": [
    19.0,
    15.9,
    13.8
   ],
   "eps_cagr": 17.5,
   "rev_cagr": 11.8
  },
  {
   "id": "BIT:BGN",
   "ticker": "BGN IM",
   "name": "Banca Generali S.p.A.",
   "sector": "Wealth / Brokers",
   "price": 60.9,
   "price_ccy": "EUR",
   "eps_ccy": "EUR",
   "fx": null,
   "eps_src": "Normalized",
   "offcycle": false,
   "price_eps_ccy": 60.9,
   "fy_labels": [
    2026,
    2027,
    2028
   ],
   "eps": [
    3.54,
    3.72,
    3.9
   ],
   "rev": [
    1044.2,
    1091.6,
    1146.3
   ],
   "n_est": [
    7,
    7,
    7
   ],
   "pe": [
    17.2,
    16.4,
    15.6
   ],
   "eps_cagr": 5.0,
   "rev_cagr": 4.8
  },
  {
   "id": "BIT:FBK",
   "ticker": "FBK IM",
   "name": "FinecoBank Banca Fineco S.p.A.",
   "sector": "Wealth / Brokers",
   "price": 21.93,
   "price_ccy": "EUR",
   "eps_ccy": "EUR",
   "fx": null,
   "eps_src": "Normalized",
   "offcycle": false,
   "price_eps_ccy": 21.93,
   "fy_labels": [
    2026,
    2027,
    2028
   ],
   "eps": [
    1.09,
    1.21,
    1.33
   ],
   "rev": [
    1429.5,
    1568.9,
    1706.5
   ],
   "n_est": [
    15,
    15,
    13
   ],
   "pe": [
    20.2,
    18.1,
    16.5
   ],
   "eps_cagr": 10.5,
   "rev_cagr": 9.3
  },
  {
   "id": "CRCL",
   "ticker": "CRCL US",
   "name": "Circle Internet Group, Inc.",
   "sector": "Wealth / Brokers",
   "price": 77.84,
   "price_ccy": "USD",
   "eps_ccy": "USD",
   "fx": null,
   "eps_src": "Normalized",
   "offcycle": false,
   "price_eps_ccy": 77.84,
   "fy_labels": [
    2026,
    2027,
    2028
   ],
   "eps": [
    1.25,
    2.23,
    3.1
   ],
   "rev": [
    3072.6,
    4308.9,
    5442.0
   ],
   "n_est": [
    8,
    12,
    5
   ],
   "pe": [
    62.2,
    35.0,
    25.1
   ],
   "eps_cagr": 57.4,
   "rev_cagr": 33.1
  },
  {
   "id": "FIGR",
   "ticker": "FIGR US",
   "name": "Figure Technology Solutions, Inc.",
   "sector": "Wealth / Brokers",
   "price": 27.93,
   "price_ccy": "USD",
   "eps_ccy": "USD",
   "fx": null,
   "eps_src": "Normalized",
   "offcycle": false,
   "price_eps_ccy": 27.93,
   "fy_labels": [
    2026,
    2027,
    2028
   ],
   "eps": [
    1.19,
    1.39,
    1.66
   ],
   "rev": [
    811.5,
    976.7,
    1200.2
   ],
   "n_est": [
    4,
    4,
    1
   ],
   "pe": [
    23.5,
    20.1,
    16.8
   ],
   "eps_cagr": 18.2,
   "rev_cagr": 21.6
  }
 ]
};
