// Auto-generated by build/build_data.py — S&P Global connector data as of 2026-06-15
window.COMP_DATA = {
 "as_of": "2026-06-15",
 "price_date": "2026-06-15",
 "fx_note": "FX as of 2026-06-15: GBPUSD 1.3405, EURUSD 1.1579, SEKUSD 0.1060.",
 "sectors": [
  "Exchanges",
  "Info Services",
  "Payments / Fintech",
  "M&A Boutiques",
  "Alternatives",
  "Traditionals",
  "Wealth / Brokers"
 ],
 "rows": [
  {
   "id": "CME",
   "ticker": "CME US",
   "name": "CME Group Inc.",
   "sector": "Exchanges",
   "price": 266.08,
   "price_ccy": "USD",
   "eps_ccy": "USD",
   "fx": null,
   "eps_src": "Normalized",
   "offcycle": false,
   "price_eps_ccy": 266.08,
   "fy_labels": [
    2026,
    2027,
    2028
   ],
   "eps": [
    12.28,
    12.92,
    13.84
   ],
   "rev": [
    7044.1,
    7345.0,
    7769.0
   ],
   "n_est": [
    15,
    15,
    8
   ],
   "pe": [
    21.7,
    20.6,
    19.2
   ],
   "eps_cagr": 6.2,
   "rev_cagr": 5.0
  },
  {
   "id": "ICE",
   "ticker": "ICE US",
   "name": "Intercontinental Exchange, Inc.",
   "sector": "Exchanges",
   "price": 140.1,
   "price_ccy": "USD",
   "eps_ccy": "USD",
   "fx": null,
   "eps_src": "Normalized",
   "offcycle": false,
   "price_eps_ccy": 140.1,
   "fy_labels": [
    2026,
    2027,
    2028
   ],
   "eps": [
    8.14,
    8.81,
    9.72
   ],
   "rev": [
    10975.5,
    11530.5,
    12211.3
   ],
   "n_est": [
    14,
    15,
    8
   ],
   "pe": [
    17.2,
    15.9,
    14.4
   ],
   "eps_cagr": 9.3,
   "rev_cagr": 5.5
  },
  {
   "id": "NDAQ",
   "ticker": "NDAQ US",
   "name": "Nasdaq, Inc.",
   "sector": "Exchanges",
   "price": 91.04,
   "price_ccy": "USD",
   "eps_ccy": "USD",
   "fx": null,
   "eps_src": "Normalized",
   "offcycle": false,
   "price_eps_ccy": 91.04,
   "fy_labels": [
    2026,
    2027,
    2028
   ],
   "eps": [
    3.94,
    4.44,
    5.07
   ],
   "rev": [
    5766.3,
    6252.4,
    6777.8
   ],
   "n_est": [
    16,
    16,
    8
   ],
   "pe": [
    23.1,
    20.5,
    18.0
   ],
   "eps_cagr": 13.4,
   "rev_cagr": 8.4
  },
  {
   "id": "CBOE",
   "ticker": "CBOE US",
   "name": "Cboe Global Markets, Inc.",
   "sector": "Exchanges",
   "price": 292.91,
   "price_ccy": "USD",
   "eps_ccy": "USD",
   "fx": null,
   "eps_src": "Normalized",
   "offcycle": false,
   "price_eps_ccy": 292.91,
   "fy_labels": [
    2026,
    2027,
    2028
   ],
   "eps": [
    13.75,
    14.72,
    16.14
   ],
   "rev": [
    2805.2,
    2907.3,
    3025.3
   ],
   "n_est": [
    12,
    12,
    5
   ],
   "pe": [
    21.3,
    19.9,
    18.1
   ],
   "eps_cagr": 8.3,
   "rev_cagr": 3.8
  },
  {
   "id": "LSE:LSEG",
   "ticker": "LSEG LN",
   "name": "London Stock Exchange Group plc",
   "sector": "Exchanges",
   "price": 91.2,
   "price_ccy": "GBP",
   "eps_ccy": "GBP",
   "fx": null,
   "eps_src": "Normalized",
   "offcycle": false,
   "price_eps_ccy": 91.2,
   "fy_labels": [
    2026,
    2027,
    2028
   ],
   "eps": [
    4.74,
    5.39,
    6.06
   ],
   "rev": [
    9880.4,
    10512.8,
    11199.7
   ],
   "n_est": [
    12,
    12,
    11
   ],
   "pe": [
    19.2,
    16.9,
    15.1
   ],
   "eps_cagr": 13.0,
   "rev_cagr": 6.5
  },
  {
   "id": "XTRA:DB1",
   "ticker": "DB1 GY",
   "name": "Deutsche B\u00f6rse AG",
   "sector": "Exchanges",
   "price": 247.7,
   "price_ccy": "EUR",
   "eps_ccy": "EUR",
   "fx": null,
   "eps_src": "Normalized",
   "offcycle": false,
   "price_eps_ccy": 247.7,
   "fy_labels": [
    2026,
    2027,
    2028
   ],
   "eps": [
    12.4,
    13.31,
    14.67
   ],
   "rev": [
    6442.5,
    6714.0,
    7168.4
   ],
   "n_est": [
    9,
    9,
    8
   ],
   "pe": [
    20.0,
    18.6,
    16.9
   ],
   "eps_cagr": 8.8,
   "rev_cagr": 5.5
  },
  {
   "id": "ENXTPA:ENX",
   "ticker": "ENX FP",
   "name": "Euronext N.V.",
   "sector": "Exchanges",
   "price": 148.3,
   "price_ccy": "EUR",
   "eps_ccy": "EUR",
   "fx": null,
   "eps_src": "Normalized",
   "offcycle": false,
   "price_eps_ccy": 148.3,
   "fy_labels": [
    2026,
    2027,
    2028
   ],
   "eps": [
    7.95,
    8.69,
    9.38
   ],
   "rev": [
    2030.7,
    2151.5,
    2279.2
   ],
   "n_est": [
    15,
    15,
    13
   ],
   "pe": [
    18.6,
    17.1,
    15.8
   ],
   "eps_cagr": 8.6,
   "rev_cagr": 5.9
  },
  {
   "id": "TW",
   "ticker": "TW US",
   "name": "Tradeweb Markets Inc.",
   "sector": "Exchanges",
   "price": 101.73,
   "price_ccy": "USD",
   "eps_ccy": "USD",
   "fx": null,
   "eps_src": "Normalized",
   "offcycle": false,
   "price_eps_ccy": 101.73,
   "fy_labels": [
    2026,
    2027,
    2028
   ],
   "eps": [
    4.05,
    4.57,
    5.17
   ],
   "rev": [
    2351.6,
    2604.3,
    2853.5
   ],
   "n_est": [
    14,
    14,
    7
   ],
   "pe": [
    25.1,
    22.3,
    19.7
   ],
   "eps_cagr": 12.9,
   "rev_cagr": 10.2
  },
  {
   "id": "MKTX",
   "ticker": "MKTX US",
   "name": "MarketAxess Holdings Inc.",
   "sector": "Exchanges",
   "price": 121.0,
   "price_ccy": "USD",
   "eps_ccy": "USD",
   "fx": null,
   "eps_src": "Normalized",
   "offcycle": false,
   "price_eps_ccy": 121.0,
   "fy_labels": [
    2026,
    2027,
    2028
   ],
   "eps": [
    8.12,
    8.92,
    10.06
   ],
   "rev": [
    901.3,
    965.1,
    1041.0
   ],
   "n_est": [
    12,
    12,
    7
   ],
   "pe": [
    14.9,
    13.6,
    12.0
   ],
   "eps_cagr": 11.3,
   "rev_cagr": 7.5
  },
  {
   "id": "MIAX",
   "ticker": "MIAX US",
   "name": "Miami International Holdings, Inc.",
   "sector": "Exchanges",
   "price": 44.11,
   "price_ccy": "USD",
   "eps_ccy": "USD",
   "fx": null,
   "eps_src": "Normalized",
   "offcycle": false,
   "price_eps_ccy": 44.11,
   "fy_labels": [
    2026,
    2027,
    2028
   ],
   "eps": [
    1.55,
    1.82,
    1.89
   ],
   "rev": [
    527.5,
    588.5,
    604.8
   ],
   "n_est": [
    6,
    7,
    3
   ],
   "pe": [
    28.5,
    24.2,
    23.3
   ],
   "eps_cagr": 10.5,
   "rev_cagr": 7.1
  },
  {
   "id": "MRX",
   "ticker": "MRX US",
   "name": "Marex Group plc",
   "sector": "Exchanges",
   "price": 62.5,
   "price_ccy": "USD",
   "eps_ccy": "USD",
   "fx": null,
   "eps_src": "Normalized",
   "offcycle": false,
   "price_eps_ccy": 62.5,
   "fy_labels": [
    2026,
    2027,
    2028
   ],
   "eps": [
    5.21,
    5.57,
    6.52
   ],
   "rev": [
    2522.6,
    2648.8,
    2948.5
   ],
   "n_est": [
    7,
    8,
    4
   ],
   "pe": [
    12.0,
    11.2,
    9.6
   ],
   "eps_cagr": 11.8,
   "rev_cagr": 8.1
  },
  {
   "id": "SPGI",
   "ticker": "SPGI US",
   "name": "S&P Global Inc.",
   "sector": "Info Services",
   "price": 424.07,
   "price_ccy": "USD",
   "eps_ccy": "USD",
   "fx": null,
   "eps_src": "Normalized",
   "offcycle": false,
   "price_eps_ccy": 424.07,
   "fy_labels": [
    2026,
    2027,
    2028
   ],
   "eps": [
    19.62,
    22.22,
    25.42
   ],
   "rev": [
    16517.9,
    17708.2,
    19010.8
   ],
   "n_est": [
    24,
    24,
    14
   ],
   "pe": [
    21.6,
    19.1,
    16.7
   ],
   "eps_cagr": 13.8,
   "rev_cagr": 7.3
  },
  {
   "id": "MCO",
   "ticker": "MCO US",
   "name": "Moody's Corporation",
   "sector": "Info Services",
   "price": 454.06,
   "price_ccy": "USD",
   "eps_ccy": "USD",
   "fx": null,
   "eps_src": "Normalized",
   "offcycle": false,
   "price_eps_ccy": 454.06,
   "fy_labels": [
    2026,
    2027,
    2028
   ],
   "eps": [
    16.7,
    18.6,
    20.72
   ],
   "rev": [
    8234.4,
    8850.7,
    9533.4
   ],
   "n_est": [
    23,
    23,
    13
   ],
   "pe": [
    27.2,
    24.4,
    21.9
   ],
   "eps_cagr": 11.4,
   "rev_cagr": 7.6
  },
  {
   "id": "MSCI",
   "ticker": "MSCI US",
   "name": "MSCI Inc.",
   "sector": "Info Services",
   "price": 611.17,
   "price_ccy": "USD",
   "eps_ccy": "USD",
   "fx": null,
   "eps_src": "Normalized",
   "offcycle": false,
   "price_eps_ccy": 611.17,
   "fy_labels": [
    2026,
    2027,
    2028
   ],
   "eps": [
    19.66,
    22.51,
    25.62
   ],
   "rev": [
    3488.4,
    3792.2,
    4103.2
   ],
   "n_est": [
    17,
    17,
    11
   ],
   "pe": [
    31.1,
    27.2,
    23.9
   ],
   "eps_cagr": 14.1,
   "rev_cagr": 8.5
  },
  {
   "id": "FDS",
   "ticker": "FDS US",
   "name": "FactSet Research Systems Inc.",
   "sector": "Info Services",
   "price": 235.86,
   "price_ccy": "USD",
   "eps_ccy": "USD",
   "fx": null,
   "eps_src": "Normalized",
   "offcycle": false,
   "price_eps_ccy": 235.86,
   "fy_labels": [
    2026,
    2027,
    2028
   ],
   "eps": [
    17.71,
    19.39,
    21.44
   ],
   "rev": [
    2464.4,
    2603.5,
    2754.6
   ],
   "n_est": [
    18,
    18,
    14
   ],
   "pe": [
    13.3,
    12.2,
    11.0
   ],
   "eps_cagr": 10.0,
   "rev_cagr": 5.7
  },
  {
   "id": "EFX",
   "ticker": "EFX US",
   "name": "Equifax Inc.",
   "sector": "Info Services",
   "price": 165.13,
   "price_ccy": "USD",
   "eps_ccy": "USD",
   "fx": null,
   "eps_src": "Normalized",
   "offcycle": false,
   "price_eps_ccy": 165.13,
   "fy_labels": [
    2026,
    2027,
    2028
   ],
   "eps": [
    8.6,
    10.28,
    12.55
   ],
   "rev": [
    6766.1,
    7383.7,
    8121.2
   ],
   "n_est": [
    24,
    24,
    14
   ],
   "pe": [
    19.2,
    16.1,
    13.2
   ],
   "eps_cagr": 20.8,
   "rev_cagr": 9.6
  },
  {
   "id": "TRU",
   "ticker": "TRU US",
   "name": "TransUnion",
   "sector": "Info Services",
   "price": 67.31,
   "price_ccy": "USD",
   "eps_ccy": "USD",
   "fx": null,
   "eps_src": "Normalized",
   "offcycle": false,
   "price_eps_ccy": 67.31,
   "fy_labels": [
    2026,
    2027,
    2028
   ],
   "eps": [
    4.78,
    5.58,
    6.57
   ],
   "rev": [
    5133.3,
    5537.3,
    5973.8
   ],
   "n_est": [
    20,
    20,
    12
   ],
   "pe": [
    14.1,
    12.1,
    10.2
   ],
   "eps_cagr": 17.3,
   "rev_cagr": 7.9
  },
  {
   "id": "LSE:EXPN",
   "ticker": "EXPN LN",
   "name": "Experian plc",
   "sector": "Info Services",
   "price": 25.63,
   "price_ccy": "GBP",
   "eps_ccy": "USD",
   "fx": 1.3405,
   "eps_src": "Normalized",
   "offcycle": true,
   "price_eps_ccy": 34.36,
   "fy_labels": [
    2027,
    2028,
    2029
   ],
   "eps": [
    2.02,
    2.32,
    2.57
   ],
   "rev": [
    9193.1,
    9951.4,
    10652.9
   ],
   "n_est": [
    17,
    15,
    12
   ],
   "pe": [
    17.0,
    14.8,
    13.4
   ],
   "eps_cagr": 12.8,
   "rev_cagr": 7.6
  },
  {
   "id": "FICO",
   "ticker": "FICO US",
   "name": "Fair Isaac Corporation",
   "sector": "Info Services",
   "price": 1181.62,
   "price_ccy": "USD",
   "eps_ccy": "USD",
   "fx": null,
   "eps_src": "Normalized",
   "offcycle": false,
   "price_eps_ccy": 1181.62,
   "fy_labels": [
    2026,
    2027,
    2028
   ],
   "eps": [
    43.07,
    54.43,
    65.9
   ],
   "rev": [
    2547.4,
    2934.2,
    3350.4
   ],
   "n_est": [
    21,
    21,
    14
   ],
   "pe": [
    27.4,
    21.7,
    17.9
   ],
   "eps_cagr": 23.7,
   "rev_cagr": 14.7
  },
  {
   "id": "VRSK",
   "ticker": "VRSK US",
   "name": "Verisk Analytics, Inc.",
   "sector": "Info Services",
   "price": 180.46,
   "price_ccy": "USD",
   "eps_ccy": "USD",
   "fx": null,
   "eps_src": "Normalized",
   "offcycle": false,
   "price_eps_ccy": 180.46,
   "fy_labels": [
    2026,
    2027,
    2028
   ],
   "eps": [
    7.65,
    8.66,
    9.66
   ],
   "rev": [
    3219.9,
    3437.3,
    3659.7
   ],
   "n_est": [
    18,
    18,
    10
   ],
   "pe": [
    23.6,
    20.8,
    18.7
   ],
   "eps_cagr": 12.4,
   "rev_cagr": 6.6
  },
  {
   "id": "V",
   "ticker": "V US",
   "name": "Visa Inc.",
   "sector": "Payments / Fintech",
   "price": 323.82,
   "price_ccy": "USD",
   "eps_ccy": "USD",
   "fx": null,
   "eps_src": "Normalized",
   "offcycle": false,
   "price_eps_ccy": 323.82,
   "fy_labels": [
    2026,
    2027,
    2028
   ],
   "eps": [
    13.14,
    14.86,
    16.82
   ],
   "rev": [
    45568.1,
    50339.4,
    55477.9
   ],
   "n_est": [
    37,
    39,
    25
   ],
   "pe": [
    24.6,
    21.8,
    19.3
   ],
   "eps_cagr": 13.1,
   "rev_cagr": 10.3
  },
  {
   "id": "MA",
   "ticker": "MA US",
   "name": "Mastercard Incorporated",
   "sector": "Payments / Fintech",
   "price": 490.64,
   "price_ccy": "USD",
   "eps_ccy": "USD",
   "fx": null,
   "eps_src": "Normalized",
   "offcycle": false,
   "price_eps_ccy": 490.64,
   "fy_labels": [
    2026,
    2027,
    2028
   ],
   "eps": [
    19.66,
    22.78,
    26.46
   ],
   "rev": [
    37084.9,
    41729.0,
    46798.1
   ],
   "n_est": [
    37,
    37,
    20
   ],
   "pe": [
    25.0,
    21.5,
    18.5
   ],
   "eps_cagr": 16.0,
   "rev_cagr": 12.3
  },
  {
   "id": "PYPL",
   "ticker": "PYPL US",
   "name": "PayPal Holdings, Inc.",
   "sector": "Payments / Fintech",
   "price": 42.49,
   "price_ccy": "USD",
   "eps_ccy": "USD",
   "fx": null,
   "eps_src": "Normalized",
   "offcycle": false,
   "price_eps_ccy": 42.49,
   "fy_labels": [
    2026,
    2027,
    2028
   ],
   "eps": [
    5.31,
    5.76,
    6.27
   ],
   "rev": [
    34330.7,
    35789.5,
    37396.4
   ],
   "n_est": [
    41,
    41,
    23
   ],
   "pe": [
    8.0,
    7.4,
    6.8
   ],
   "eps_cagr": 8.7,
   "rev_cagr": 4.4
  },
  {
   "id": "XYZ",
   "ticker": "XYZ US",
   "name": "Block, Inc.",
   "sector": "Payments / Fintech",
   "price": 74.35,
   "price_ccy": "USD",
   "eps_ccy": "USD",
   "fx": null,
   "eps_src": "Normalized",
   "offcycle": false,
   "price_eps_ccy": 74.35,
   "fy_labels": [
    2026,
    2027,
    2028
   ],
   "eps": [
    3.9,
    4.98,
    6.16
   ],
   "rev": [
    26224.4,
    29299.6,
    32898.5
   ],
   "n_est": [
    38,
    40,
    20
   ],
   "pe": [
    19.1,
    14.9,
    12.1
   ],
   "eps_cagr": 25.7,
   "rev_cagr": 12.0
  },
  {
   "id": "ENXTAM:ADYEN",
   "ticker": "ADYEN NA",
   "name": "Adyen N.V.",
   "sector": "Payments / Fintech",
   "price": 858.9,
   "price_ccy": "EUR",
   "eps_ccy": "USD",
   "fx": 1.1579,
   "eps_src": "Normalized",
   "offcycle": false,
   "price_eps_ccy": 994.52,
   "fy_labels": [
    2026,
    2027,
    2028
   ],
   "eps": [
    38.76,
    47.25,
    57.97
   ],
   "rev": [
    2828.2,
    3419.3,
    4110.5
   ],
   "n_est": [
    30,
    27,
    22
   ],
   "pe": [
    25.7,
    21.0,
    17.2
   ],
   "eps_cagr": 22.3,
   "rev_cagr": 20.6
  },
  {
   "id": "TOST",
   "ticker": "TOST US",
   "name": "Toast, Inc.",
   "sector": "Payments / Fintech",
   "price": 25.05,
   "price_ccy": "USD",
   "eps_ccy": "USD",
   "fx": null,
   "eps_src": "Normalized",
   "offcycle": false,
   "price_eps_ccy": 25.05,
   "fy_labels": [
    2026,
    2027,
    2028
   ],
   "eps": [
    1.35,
    1.7,
    2.19
   ],
   "rev": [
    7386.1,
    8721.3,
    10184.6
   ],
   "n_est": [
    16,
    16,
    8
   ],
   "pe": [
    18.6,
    14.8,
    11.5
   ],
   "eps_cagr": 27.2,
   "rev_cagr": 17.4
  },
  {
   "id": "SHOP",
   "ticker": "SHOP US",
   "name": "Shopify Inc.",
   "sector": "Payments / Fintech",
   "price": 112.49,
   "price_ccy": "USD",
   "eps_ccy": "USD",
   "fx": null,
   "eps_src": "Normalized",
   "offcycle": false,
   "price_eps_ccy": 112.49,
   "fy_labels": [
    2026,
    2027,
    2028
   ],
   "eps": [
    1.84,
    2.33,
    3.26
   ],
   "rev": [
    14797.8,
    18323.4,
    23017.4
   ],
   "n_est": [
    40,
    38,
    17
   ],
   "pe": [
    61.1,
    48.3,
    34.5
   ],
   "eps_cagr": 33.2,
   "rev_cagr": 24.7
  },
  {
   "id": "SOFI",
   "ticker": "SOFI US",
   "name": "SoFi Technologies, Inc.",
   "sector": "Payments / Fintech",
   "price": 17.13,
   "price_ccy": "USD",
   "eps_ccy": "USD",
   "fx": null,
   "eps_src": "Normalized",
   "offcycle": false,
   "price_eps_ccy": 17.13,
   "fy_labels": [
    2026,
    2027,
    2028
   ],
   "eps": [
    0.59,
    0.82,
    1.08
   ],
   "rev": [
    4679.1,
    5738.2,
    7025.0
   ],
   "n_est": [
    9,
    8,
    4
   ],
   "pe": [
    29.1,
    21.0,
    15.9
   ],
   "eps_cagr": 35.3,
   "rev_cagr": 22.5
  },
  {
   "id": "FISV",
   "ticker": "FISV US",
   "name": "Fiserv, Inc.",
   "sector": "Payments / Fintech",
   "price": 47.91,
   "price_ccy": "USD",
   "eps_ccy": "USD",
   "fx": null,
   "eps_src": "Normalized",
   "offcycle": false,
   "price_eps_ccy": 47.91,
   "fy_labels": [
    2026,
    2027,
    2028
   ],
   "eps": [
    8.12,
    8.95,
    10.06
   ],
   "rev": [
    20040.4,
    20861.2,
    21642.0
   ],
   "n_est": [
    35,
    35,
    19
   ],
   "pe": [
    5.9,
    5.4,
    4.8
   ],
   "eps_cagr": 11.3,
   "rev_cagr": 3.9
  },
  {
   "id": "FIS",
   "ticker": "FIS US",
   "name": "Fidelity National Information Services, Inc.",
   "sector": "Payments / Fintech",
   "price": 38.97,
   "price_ccy": "USD",
   "eps_ccy": "USD",
   "fx": null,
   "eps_src": "Normalized",
   "offcycle": false,
   "price_eps_ccy": 38.97,
   "fy_labels": [
    2026,
    2027,
    2028
   ],
   "eps": [
    6.27,
    6.85,
    7.48
   ],
   "rev": [
    13797.4,
    14442.4,
    15039.4
   ],
   "n_est": [
    25,
    25,
    11
   ],
   "pe": [
    6.2,
    5.7,
    5.2
   ],
   "eps_cagr": 9.2,
   "rev_cagr": 4.4
  },
  {
   "id": "GPN",
   "ticker": "GPN US",
   "name": "Global Payments Inc.",
   "sector": "Payments / Fintech",
   "price": 67.48,
   "price_ccy": "USD",
   "eps_ccy": "USD",
   "fx": null,
   "eps_src": "Normalized",
   "offcycle": false,
   "price_eps_ccy": 67.48,
   "fy_labels": [
    2026,
    2027,
    2028
   ],
   "eps": [
    13.85,
    16.18,
    18.66
   ],
   "rev": [
    12435.6,
    13137.4,
    13756.8
   ],
   "n_est": [
    32,
    32,
    18
   ],
   "pe": [
    4.9,
    4.2,
    3.6
   ],
   "eps_cagr": 16.1,
   "rev_cagr": 5.2
  },
  {
   "id": "JKHY",
   "ticker": "JKHY US",
   "name": "Jack Henry & Associates, Inc.",
   "sector": "Payments / Fintech",
   "price": 130.35,
   "price_ccy": "USD",
   "eps_ccy": "USD",
   "fx": null,
   "eps_src": "Normalized",
   "offcycle": false,
   "price_eps_ccy": 130.35,
   "fy_labels": [
    2026,
    2027,
    2028
   ],
   "eps": [
    6.55,
    7.09,
    7.66
   ],
   "rev": [
    2529.0,
    2680.6,
    2860.6
   ],
   "n_est": [
    7,
    9,
    7
   ],
   "pe": [
    19.9,
    18.4,
    17.0
   ],
   "eps_cagr": 8.2,
   "rev_cagr": 6.4
  },
  {
   "id": "CPAY",
   "ticker": "CPAY US",
   "name": "Corpay, Inc.",
   "sector": "Payments / Fintech",
   "price": 353.47,
   "price_ccy": "USD",
   "eps_ccy": "USD",
   "fx": null,
   "eps_src": "Normalized",
   "offcycle": false,
   "price_eps_ccy": 353.47,
   "fy_labels": [
    2026,
    2027,
    2028
   ],
   "eps": [
    26.77,
    30.61,
    35.46
   ],
   "rev": [
    5303.2,
    5823.4,
    6336.4
   ],
   "n_est": [
    15,
    15,
    5
   ],
   "pe": [
    13.2,
    11.5,
    10.0
   ],
   "eps_cagr": 15.1,
   "rev_cagr": 9.3
  },
  {
   "id": "WEX",
   "ticker": "WEX US",
   "name": "WEX Inc.",
   "sector": "Payments / Fintech",
   "price": 131.66,
   "price_ccy": "USD",
   "eps_ccy": "USD",
   "fx": null,
   "eps_src": "Normalized",
   "offcycle": false,
   "price_eps_ccy": 131.66,
   "fy_labels": [
    2026,
    2027,
    2028
   ],
   "eps": [
    19.3,
    20.31,
    21.99
   ],
   "rev": [
    2848.6,
    2916.6,
    3028.7
   ],
   "n_est": [
    14,
    14,
    6
   ],
   "pe": [
    6.8,
    6.5,
    6.0
   ],
   "eps_cagr": 6.8,
   "rev_cagr": 3.1
  },
  {
   "id": "AFRM",
   "ticker": "AFRM US",
   "name": "Affirm Holdings, Inc.",
   "sector": "Payments / Fintech",
   "price": 71.9,
   "price_ccy": "USD",
   "eps_ccy": "USD",
   "fx": null,
   "eps_src": "Normalized",
   "offcycle": false,
   "price_eps_ccy": 71.9,
   "fy_labels": [
    2026,
    2027,
    2028
   ],
   "eps": [
    3.1,
    3.78,
    4.73
   ],
   "rev": [
    4202.8,
    5262.7,
    6550.6
   ],
   "n_est": [
    8,
    8,
    8
   ],
   "pe": [
    23.2,
    19.0,
    15.2
   ],
   "eps_cagr": 23.5,
   "rev_cagr": 24.8
  },
  {
   "id": "KLAR",
   "ticker": "KLAR US",
   "name": "Klarna Group plc",
   "sector": "Payments / Fintech",
   "price": 17.6,
   "price_ccy": "USD",
   "eps_ccy": "USD",
   "fx": null,
   "eps_src": "Normalized",
   "offcycle": false,
   "price_eps_ccy": 17.6,
   "fy_labels": [
    2026,
    2027,
    2028
   ],
   "eps": [
    0.18,
    0.92,
    1.44
   ],
   "rev": [
    4424.6,
    5304.5,
    6265.2
   ],
   "n_est": [
    7,
    8,
    6
   ],
   "pe": [
    95.5,
    19.1,
    12.2
   ],
   "eps_cagr": 179.4,
   "rev_cagr": 19.0
  },
  {
   "id": "BILL",
   "ticker": "BILL US",
   "name": "BILL Holdings, Inc.",
   "sector": "Payments / Fintech",
   "price": 33.54,
   "price_ccy": "USD",
   "eps_ccy": "USD",
   "fx": null,
   "eps_src": "Normalized",
   "offcycle": false,
   "price_eps_ccy": 33.54,
   "fy_labels": [
    2026,
    2027,
    2028
   ],
   "eps": [
    2.64,
    3.34,
    4.06
   ],
   "rev": [
    1645.5,
    1853.1,
    2103.5
   ],
   "n_est": [
    21,
    21,
    11
   ],
   "pe": [
    12.7,
    10.0,
    8.3
   ],
   "eps_cagr": 24.0,
   "rev_cagr": 13.1
  },
  {
   "id": "CHYM",
   "ticker": "CHYM US",
   "name": "Chime Financial, Inc.",
   "sector": "Payments / Fintech",
   "price": 17.64,
   "price_ccy": "USD",
   "eps_ccy": "USD",
   "fx": null,
   "eps_src": "GAAP",
   "offcycle": false,
   "price_eps_ccy": 17.64,
   "fy_labels": [
    2026,
    2027,
    2028
   ],
   "eps": [
    0.32,
    0.78,
    1.04
   ],
   "rev": [
    2679.7,
    3194.5,
    3728.7
   ],
   "n_est": [
    14,
    15,
    7
   ],
   "pe": [
    55.1,
    22.7,
    16.9
   ],
   "eps_cagr": 80.5,
   "rev_cagr": 18.0
  },
  {
   "id": "MQ",
   "ticker": "MQ US",
   "name": "Marqeta, Inc.",
   "sector": "Payments / Fintech",
   "price": 3.89,
   "price_ccy": "USD",
   "eps_ccy": "USD",
   "fx": null,
   "eps_src": "Normalized",
   "offcycle": false,
   "price_eps_ccy": 3.89,
   "fy_labels": [
    2026,
    2027,
    2028
   ],
   "eps": [
    0.03,
    0.11,
    0.11
   ],
   "rev": [
    708.8,
    828.1,
    950.8
   ],
   "n_est": [
    2,
    3,
    1
   ],
   "pe": [
    142.4,
    37.0,
    35.4
   ],
   "eps_cagr": 100.7,
   "rev_cagr": 15.8
  },
  {
   "id": "FOUR",
   "ticker": "FOUR US",
   "name": "Shift4 Payments, Inc.",
   "sector": "Payments / Fintech",
   "price": 39.94,
   "price_ccy": "USD",
   "eps_ccy": "USD",
   "fx": null,
   "eps_src": "Normalized",
   "offcycle": false,
   "price_eps_ccy": 39.94,
   "fy_labels": [
    2026,
    2027,
    2028
   ],
   "eps": [
    5.59,
    6.76,
    7.87
   ],
   "rev": [
    5096.5,
    5797.3,
    6515.5
   ],
   "n_est": [
    23,
    22,
    9
   ],
   "pe": [
    7.1,
    5.9,
    5.1
   ],
   "eps_cagr": 18.6,
   "rev_cagr": 13.1
  },
  {
   "id": "LSE:WISE",
   "ticker": "WISE LN",
   "name": "Wise Group plc",
   "sector": "Payments / Fintech",
   "price": 8.26,
   "price_ccy": "GBP",
   "eps_ccy": "GBP",
   "fx": null,
   "eps_src": "Normalized",
   "offcycle": false,
   "price_eps_ccy": 8.26,
   "fy_labels": [
    2026,
    2027,
    2028
   ],
   "eps": [
    0.47,
    0.57,
    0.68
   ],
   "rev": [
    1869.3,
    2275.2,
    2726.0
   ],
   "n_est": [
    19,
    19,
    17
   ],
   "pe": [
    17.5,
    14.5,
    12.2
   ],
   "eps_cagr": 19.9,
   "rev_cagr": 20.8
  },
  {
   "id": "RELY",
   "ticker": "RELY LN",
   "name": "Remitly Global, Inc.",
   "sector": "Payments / Fintech",
   "price": 19.63,
   "price_ccy": "USD",
   "eps_ccy": "USD",
   "fx": null,
   "eps_src": "Normalized",
   "offcycle": false,
   "price_eps_ccy": 19.63,
   "fy_labels": [
    2026,
    2027,
    2028
   ],
   "eps": [
    1.37,
    1.65,
    1.98
   ],
   "rev": [
    1972.0,
    2348.5,
    2764.4
   ],
   "n_est": [
    3,
    3,
    3
   ],
   "pe": [
    14.4,
    11.9,
    9.9
   ],
   "eps_cagr": 20.3,
   "rev_cagr": 18.4
  },
  {
   "id": "WU",
   "ticker": "WU US",
   "name": "The Western Union Company",
   "sector": "Payments / Fintech",
   "price": 7.49,
   "price_ccy": "USD",
   "eps_ccy": "USD",
   "fx": null,
   "eps_src": "Normalized",
   "offcycle": false,
   "price_eps_ccy": 7.49,
   "fy_labels": [
    2026,
    2027,
    2028
   ],
   "eps": [
    1.75,
    1.92,
    2.06
   ],
   "rev": [
    4275.1,
    4474.2,
    4641.9
   ],
   "n_est": [
    17,
    17,
    9
   ],
   "pe": [
    4.3,
    3.9,
    3.6
   ],
   "eps_cagr": 8.4,
   "rev_cagr": 4.2
  },
  {
   "id": "LAZ",
   "ticker": "LAZ US",
   "name": "Lazard, Inc.",
   "sector": "M&A Boutiques",
   "price": 44.06,
   "price_ccy": "USD",
   "eps_ccy": "USD",
   "fx": null,
   "eps_src": "Normalized",
   "offcycle": false,
   "price_eps_ccy": 44.06,
   "fy_labels": [
    2026,
    2027,
    2028
   ],
   "eps": [
    2.85,
    4.39,
    5.62
   ],
   "rev": [
    3381.9,
    4007.4,
    4388.6
   ],
   "n_est": [
    9,
    10,
    3
   ],
   "pe": [
    15.5,
    10.0,
    7.8
   ],
   "eps_cagr": 40.5,
   "rev_cagr": 13.9
  },
  {
   "id": "EVR",
   "ticker": "EVR US",
   "name": "Evercore Inc.",
   "sector": "M&A Boutiques",
   "price": 365.53,
   "price_ccy": "USD",
   "eps_ccy": "USD",
   "fx": null,
   "eps_src": "Normalized",
   "offcycle": false,
   "price_eps_ccy": 365.53,
   "fy_labels": [
    2026,
    2027,
    2028
   ],
   "eps": [
    19.22,
    23.01,
    27.05
   ],
   "rev": [
    4706.1,
    5365.9,
    5412.4
   ],
   "n_est": [
    10,
    10,
    3
   ],
   "pe": [
    19.0,
    15.9,
    13.5
   ],
   "eps_cagr": 18.7,
   "rev_cagr": 7.2
  },
  {
   "id": "MC",
   "ticker": "MC US",
   "name": "Moelis & Company",
   "sector": "M&A Boutiques",
   "price": 69.09,
   "price_ccy": "USD",
   "eps_ccy": "USD",
   "fx": null,
   "eps_src": "Normalized",
   "offcycle": false,
   "price_eps_ccy": 69.09,
   "fy_labels": [
    2026,
    2027,
    2028
   ],
   "eps": [
    3.09,
    4.09,
    4.41
   ],
   "rev": [
    1692.0,
    2014.3,
    2201.1
   ],
   "n_est": [
    11,
    11,
    3
   ],
   "pe": [
    22.3,
    16.9,
    15.7
   ],
   "eps_cagr": 19.3,
   "rev_cagr": 14.1
  },
  {
   "id": "HLI",
   "ticker": "HLI US",
   "name": "Houlihan Lokey, Inc.",
   "sector": "M&A Boutiques",
   "price": 139.83,
   "price_ccy": "USD",
   "eps_ccy": "USD",
   "fx": null,
   "eps_src": "Normalized",
   "offcycle": true,
   "price_eps_ccy": 139.83,
   "fy_labels": [
    2027,
    2028,
    2029
   ],
   "eps": [
    8.21,
    9.44,
    10.73
   ],
   "rev": [
    2946.2,
    3336.1,
    3581.5
   ],
   "n_est": [
    10,
    9,
    3
   ],
   "pe": [
    17.0,
    14.8,
    13.0
   ],
   "eps_cagr": 14.3,
   "rev_cagr": 10.3
  },
  {
   "id": "PWP",
   "ticker": "PWP US",
   "name": "Perella Weinberg Partners",
   "sector": "M&A Boutiques",
   "price": 16.01,
   "price_ccy": "USD",
   "eps_ccy": "USD",
   "fx": null,
   "eps_src": "Normalized",
   "offcycle": false,
   "price_eps_ccy": 16.01,
   "fy_labels": [
    2026,
    2027,
    2028
   ],
   "eps": [
    1.01,
    1.5,
    1.79
   ],
   "rev": [
    883.6,
    1098.4,
    1184.8
   ],
   "n_est": [
    4,
    4,
    1
   ],
   "pe": [
    15.9,
    10.6,
    8.9
   ],
   "eps_cagr": 33.1,
   "rev_cagr": 15.8
  },
  {
   "id": "PJT",
   "ticker": "PJT US",
   "name": "PJT Partners Inc.",
   "sector": "M&A Boutiques",
   "price": 156.37,
   "price_ccy": "USD",
   "eps_ccy": "USD",
   "fx": null,
   "eps_src": "Normalized",
   "offcycle": false,
   "price_eps_ccy": 156.37,
   "fy_labels": [
    2026,
    2027,
    2028
   ],
   "eps": [
    7.52,
    8.55,
    9.57
   ],
   "rev": [
    1871.6,
    2067.7,
    2174.9
   ],
   "n_est": [
    7,
    7,
    2
   ],
   "pe": [
    20.8,
    18.3,
    16.3
   ],
   "eps_cagr": 12.8,
   "rev_cagr": 7.8
  },
  {
   "id": "PIPR",
   "ticker": "PIPR US",
   "name": "Piper Sandler Companies",
   "sector": "M&A Boutiques",
   "price": 79.52,
   "price_ccy": "USD",
   "eps_ccy": "USD",
   "fx": null,
   "eps_src": "Normalized",
   "offcycle": false,
   "price_eps_ccy": 79.52,
   "fy_labels": [
    2026,
    2027,
    2028
   ],
   "eps": [
    4.71,
    5.62,
    6.31
   ],
   "rev": [
    2067.2,
    2315.6,
    2486.7
   ],
   "n_est": [
    5,
    5,
    1
   ],
   "pe": [
    16.9,
    14.2,
    12.6
   ],
   "eps_cagr": 15.7,
   "rev_cagr": 9.7
  },
  {
   "id": "SWX:PGHN",
   "ticker": "PGHN SW",
   "name": "Partners Group Holding AG",
   "sector": "Alternatives",
   "price": 714.4,
   "price_ccy": "CHF",
   "eps_ccy": "CHF",
   "fx": null,
   "eps_src": "Normalized",
   "offcycle": false,
   "price_eps_ccy": 714.4,
   "fy_labels": [
    2026,
    2027,
    2028
   ],
   "eps": [
    46.7,
    53.17,
    60.24
   ],
   "rev": [
    2535.5,
    2886.7,
    3262.8
   ],
   "n_est": [
    13,
    13,
    11
   ],
   "pe": [
    15.3,
    13.4,
    11.9
   ],
   "eps_cagr": 13.6,
   "rev_cagr": 13.4
  },
  {
   "id": "OM:EQT",
   "ticker": "EQT SS",
   "name": "EQT AB (publ)",
   "sector": "Alternatives",
   "price": 290.0,
   "price_ccy": "SEK",
   "eps_ccy": "EUR",
   "fx": 0.0916,
   "eps_src": "Normalized",
   "offcycle": false,
   "price_eps_ccy": 26.56,
   "fy_labels": [
    2026,
    2027,
    2028
   ],
   "eps": [
    1.22,
    1.66,
    1.93
   ],
   "rev": [
    2870.8,
    3815.8,
    4196.5
   ],
   "n_est": [
    9,
    8,
    7
   ],
   "pe": [
    21.7,
    16.0,
    13.8
   ],
   "eps_cagr": 25.6,
   "rev_cagr": 20.9
  },
  {
   "id": "ENXTAM:CVC",
   "ticker": "CVC NA",
   "name": "CVC Capital Partners plc",
   "sector": "Alternatives",
   "price": 13.26,
   "price_ccy": "EUR",
   "eps_ccy": "EUR",
   "fx": null,
   "eps_src": "Normalized",
   "offcycle": false,
   "price_eps_ccy": 13.26,
   "fy_labels": [
    2026,
    2027,
    2028
   ],
   "eps": [
    0.84,
    0.97,
    1.32
   ],
   "rev": [
    1884.5,
    2107.7,
    2574.5
   ],
   "n_est": [
    9,
    9,
    7
   ],
   "pe": [
    15.7,
    13.7,
    10.0
   ],
   "eps_cagr": 25.2,
   "rev_cagr": 16.9
  },
  {
   "id": "LSE:ICG",
   "ticker": "ICG LN",
   "name": "ICG plc",
   "sector": "Alternatives",
   "price": 17.97,
   "price_ccy": "GBP",
   "eps_ccy": "GBP",
   "fx": null,
   "eps_src": "Normalized",
   "offcycle": true,
   "price_eps_ccy": 17.97,
   "fy_labels": [
    2027,
    2028,
    2029
   ],
   "eps": [
    1.75,
    1.93,
    2.19
   ],
   "rev": [
    1043.1,
    1137.7,
    1242.4
   ],
   "n_est": [
    10,
    12,
    5
   ],
   "pe": [
    10.3,
    9.3,
    8.2
   ],
   "eps_cagr": 12.0,
   "rev_cagr": 9.1
  },
  {
   "id": "ARES",
   "ticker": "ARES US",
   "name": "Ares Management Corporation",
   "sector": "Alternatives",
   "price": 135.36,
   "price_ccy": "USD",
   "eps_ccy": "USD",
   "fx": null,
   "eps_src": "Normalized",
   "offcycle": false,
   "price_eps_ccy": 135.36,
   "fy_labels": [
    2026,
    2027,
    2028
   ],
   "eps": [
    5.94,
    7.32,
    8.46
   ],
   "rev": [
    4921.0,
    6105.8,
    7159.2
   ],
   "n_est": [
    12,
    14,
    6
   ],
   "pe": [
    22.8,
    18.5,
    16.0
   ],
   "eps_cagr": 19.3,
   "rev_cagr": 20.6
  },
  {
   "id": "APO",
   "ticker": "APO US",
   "name": "Apollo Global Management, Inc.",
   "sector": "Alternatives",
   "price": 136.11,
   "price_ccy": "USD",
   "eps_ccy": "USD",
   "fx": null,
   "eps_src": "Normalized",
   "offcycle": false,
   "price_eps_ccy": 136.11,
   "fy_labels": [
    2026,
    2027,
    2028
   ],
   "eps": [
    8.88,
    10.61,
    12.48
   ],
   "rev": [
    5483.5,
    6279.2,
    null
   ],
   "n_est": [
    18,
    18,
    6
   ],
   "pe": [
    15.3,
    12.8,
    10.9
   ],
   "eps_cagr": 18.5,
   "rev_cagr": null
  },
  {
   "id": "BX",
   "ticker": "BX US",
   "name": "Blackstone Inc.",
   "sector": "Alternatives",
   "price": 124.63,
   "price_ccy": "USD",
   "eps_ccy": "USD",
   "fx": null,
   "eps_src": "Normalized",
   "offcycle": false,
   "price_eps_ccy": 124.63,
   "fy_labels": [
    2026,
    2027,
    2028
   ],
   "eps": [
    5.94,
    7.54,
    8.07
   ],
   "rev": [
    14962.9,
    18935.5,
    21342.8
   ],
   "n_est": [
    19,
    19,
    6
   ],
   "pe": [
    21.0,
    16.5,
    15.4
   ],
   "eps_cagr": 16.6,
   "rev_cagr": 19.4
  },
  {
   "id": "KKR",
   "ticker": "KKR US",
   "name": "KKR & Co. Inc.",
   "sector": "Alternatives",
   "price": 98.08,
   "price_ccy": "USD",
   "eps_ccy": "USD",
   "fx": null,
   "eps_src": "Normalized",
   "offcycle": false,
   "price_eps_ccy": 98.08,
   "fy_labels": [
    2026,
    2027,
    2028
   ],
   "eps": [
    6.04,
    7.4,
    8.59
   ],
   "rev": [
    10340.0,
    12218.3,
    13699.3
   ],
   "n_est": [
    20,
    20,
    8
   ],
   "pe": [
    16.2,
    13.3,
    11.4
   ],
   "eps_cagr": 19.3,
   "rev_cagr": 15.1
  },
  {
   "id": "OWL",
   "ticker": "OWL US",
   "name": "Blue Owl Capital Inc.",
   "sector": "Alternatives",
   "price": 9.61,
   "price_ccy": "USD",
   "eps_ccy": "USD",
   "fx": null,
   "eps_src": "Normalized",
   "offcycle": false,
   "price_eps_ccy": 9.61,
   "fy_labels": [
    2026,
    2027,
    2028
   ],
   "eps": [
    0.88,
    0.98,
    1.16
   ],
   "rev": [
    2890.8,
    3213.7,
    3574.9
   ],
   "n_est": [
    14,
    15,
    5
   ],
   "pe": [
    10.9,
    9.8,
    8.3
   ],
   "eps_cagr": 14.5,
   "rev_cagr": 11.2
  },
  {
   "id": "CG",
   "ticker": "CG US",
   "name": "The Carlyle Group Inc.",
   "sector": "Alternatives",
   "price": 46.24,
   "price_ccy": "USD",
   "eps_ccy": "USD",
   "fx": null,
   "eps_src": "Normalized",
   "offcycle": false,
   "price_eps_ccy": 46.24,
   "fy_labels": [
    2026,
    2027,
    2028
   ],
   "eps": [
    4.09,
    5.22,
    5.67
   ],
   "rev": [
    3791.1,
    5043.0,
    5597.6
   ],
   "n_est": [
    14,
    13,
    3
   ],
   "pe": [
    11.3,
    8.9,
    8.2
   ],
   "eps_cagr": 17.8,
   "rev_cagr": 21.5
  },
  {
   "id": "BAM",
   "ticker": "BAM US",
   "name": "Brookfield Asset Management Ltd.",
   "sector": "Alternatives",
   "price": 48.19,
   "price_ccy": "USD",
   "eps_ccy": "USD",
   "fx": null,
   "eps_src": "Normalized",
   "offcycle": false,
   "price_eps_ccy": 48.19,
   "fy_labels": [
    2026,
    2027,
    2028
   ],
   "eps": [
    1.84,
    2.18,
    2.57
   ],
   "rev": [
    6020.4,
    7000.1,
    7944.4
   ],
   "n_est": [
    17,
    17,
    6
   ],
   "pe": [
    26.2,
    22.1,
    18.7
   ],
   "eps_cagr": 18.3,
   "rev_cagr": 14.9
  },
  {
   "id": "TPG",
   "ticker": "TPG US",
   "name": "TPG Inc.",
   "sector": "Alternatives",
   "price": 43.49,
   "price_ccy": "USD",
   "eps_ccy": "USD",
   "fx": null,
   "eps_src": "Normalized",
   "offcycle": false,
   "price_eps_ccy": 43.49,
   "fy_labels": [
    2026,
    2027,
    2028
   ],
   "eps": [
    2.83,
    3.56,
    4.17
   ],
   "rev": [
    2473.7,
    2992.3,
    null
   ],
   "n_est": [
    13,
    13,
    3
   ],
   "pe": [
    15.4,
    12.2,
    10.4
   ],
   "eps_cagr": 21.3,
   "rev_cagr": null
  },
  {
   "id": "STEP",
   "ticker": "STEP US",
   "name": "StepStone Group Inc.",
   "sector": "Alternatives",
   "price": 47.05,
   "price_ccy": "USD",
   "eps_ccy": "USD",
   "fx": null,
   "eps_src": "Normalized",
   "offcycle": true,
   "price_eps_ccy": 47.05,
   "fy_labels": [
    2027,
    2028,
    2029
   ],
   "eps": [
    2.5,
    3.31,
    3.48
   ],
   "rev": [
    1557.9,
    1774.2,
    1768.3
   ],
   "n_est": [
    8,
    7,
    1
   ],
   "pe": [
    18.8,
    14.2,
    13.5
   ],
   "eps_cagr": 18.0,
   "rev_cagr": 6.5
  },
  {
   "id": "HLNE",
   "ticker": "HLNE US",
   "name": "Hamilton Lane Incorporated",
   "sector": "Alternatives",
   "price": 81.99,
   "price_ccy": "USD",
   "eps_ccy": "USD",
   "fx": null,
   "eps_src": "Normalized",
   "offcycle": true,
   "price_eps_ccy": 81.99,
   "fy_labels": [
    2027,
    2028,
    2029
   ],
   "eps": [
    6.1,
    7.4,
    8.17
   ],
   "rev": [
    886.4,
    1050.9,
    1144.4
   ],
   "n_est": [
    7,
    5,
    1
   ],
   "pe": [
    13.4,
    11.1,
    10.0
   ],
   "eps_cagr": 15.7,
   "rev_cagr": 13.6
  },
  {
   "id": "BLK",
   "ticker": "BLK US",
   "name": "BlackRock, Inc.",
   "sector": "Traditionals",
   "price": 1042.87,
   "price_ccy": "USD",
   "eps_ccy": "USD",
   "fx": null,
   "eps_src": "Normalized",
   "offcycle": false,
   "price_eps_ccy": 1042.87,
   "fy_labels": [
    2026,
    2027,
    2028
   ],
   "eps": [
    53.17,
    60.72,
    70.54
   ],
   "rev": [
    27912.2,
    30842.1,
    34699.1
   ],
   "n_est": [
    15,
    15,
    6
   ],
   "pe": [
    19.6,
    17.2,
    14.8
   ],
   "eps_cagr": 15.2,
   "rev_cagr": 11.5
  },
  {
   "id": "TROW",
   "ticker": "TROW US",
   "name": "T. Rowe Price Group, Inc.",
   "sector": "Traditionals",
   "price": 108.61,
   "price_ccy": "USD",
   "eps_ccy": "USD",
   "fx": null,
   "eps_src": "Normalized",
   "offcycle": false,
   "price_eps_ccy": 108.61,
   "fy_labels": [
    2026,
    2027,
    2028
   ],
   "eps": [
    9.57,
    9.67,
    9.68
   ],
   "rev": [
    7543.7,
    7661.1,
    7784.4
   ],
   "n_est": [
    13,
    13,
    4
   ],
   "pe": [
    11.4,
    11.2,
    11.2
   ],
   "eps_cagr": 0.6,
   "rev_cagr": 1.6
  },
  {
   "id": "XTRA:DWS",
   "ticker": "DWS GY",
   "name": "DWS Group GmbH & Co. KGaA",
   "sector": "Traditionals",
   "price": 60.6,
   "price_ccy": "EUR",
   "eps_ccy": "EUR",
   "fx": null,
   "eps_src": "Normalized",
   "offcycle": false,
   "price_eps_ccy": 60.6,
   "fy_labels": [
    2026,
    2027,
    2028
   ],
   "eps": [
    5.06,
    5.26,
    5.77
   ],
   "rev": [
    3252.1,
    3325.4,
    3516.6
   ],
   "n_est": [
    7,
    8,
    8
   ],
   "pe": [
    12.0,
    11.5,
    10.5
   ],
   "eps_cagr": 6.9,
   "rev_cagr": 4.0
  },
  {
   "id": "ENXTPA:AMUN",
   "ticker": "AMUN FP",
   "name": "Amundi S.A.",
   "sector": "Traditionals",
   "price": 83.25,
   "price_ccy": "EUR",
   "eps_ccy": "EUR",
   "fx": null,
   "eps_src": "Normalized",
   "offcycle": false,
   "price_eps_ccy": 83.25,
   "fy_labels": [
    2026,
    2027,
    2028
   ],
   "eps": [
    7.18,
    7.61,
    7.84
   ],
   "rev": [
    3488.8,
    3537.7,
    3619.3
   ],
   "n_est": [
    14,
    14,
    13
   ],
   "pe": [
    11.6,
    10.9,
    10.6
   ],
   "eps_cagr": 4.5,
   "rev_cagr": 1.9
  },
  {
   "id": "AB",
   "ticker": "AB US",
   "name": "AllianceBernstein Holding L.P.",
   "sector": "Traditionals",
   "price": 36.03,
   "price_ccy": "USD",
   "eps_ccy": "USD",
   "fx": null,
   "eps_src": "Normalized",
   "offcycle": false,
   "price_eps_ccy": 36.03,
   "fy_labels": [
    2026,
    2027,
    2028
   ],
   "eps": [
    3.47,
    3.83,
    4.22
   ],
   "rev": [
    3698.7,
    3980.1,
    4411.4
   ],
   "n_est": [
    7,
    7,
    2
   ],
   "pe": [
    10.4,
    9.4,
    8.5
   ],
   "eps_cagr": 10.3,
   "rev_cagr": 9.2
  },
  {
   "id": "BEN",
   "ticker": "BEN US",
   "name": "Franklin Resources, Inc.",
   "sector": "Traditionals",
   "price": 32.51,
   "price_ccy": "USD",
   "eps_ccy": "USD",
   "fx": null,
   "eps_src": "Normalized",
   "offcycle": false,
   "price_eps_ccy": 32.51,
   "fy_labels": [
    2026,
    2027,
    2028
   ],
   "eps": [
    2.75,
    2.98,
    3.29
   ],
   "rev": [
    9090.0,
    9180.3,
    8918.6
   ],
   "n_est": [
    10,
    11,
    4
   ],
   "pe": [
    11.8,
    10.9,
    9.9
   ],
   "eps_cagr": 9.3,
   "rev_cagr": -0.9
  },
  {
   "id": "IVZ",
   "ticker": "IVZ US",
   "name": "Invesco Ltd.",
   "sector": "Traditionals",
   "price": 29.1,
   "price_ccy": "USD",
   "eps_ccy": "USD",
   "fx": null,
   "eps_src": "Normalized",
   "offcycle": false,
   "price_eps_ccy": 29.1,
   "fy_labels": [
    2026,
    2027,
    2028
   ],
   "eps": [
    2.6,
    2.99,
    3.31
   ],
   "rev": [
    5181.2,
    5495.4,
    null
   ],
   "n_est": [
    12,
    12,
    4
   ],
   "pe": [
    11.2,
    9.7,
    8.8
   ],
   "eps_cagr": 13.0,
   "rev_cagr": null
  },
  {
   "id": "AMP",
   "ticker": "AMP US",
   "name": "Ameriprise Financial, Inc.",
   "sector": "Traditionals",
   "price": 459.88,
   "price_ccy": "USD",
   "eps_ccy": "USD",
   "fx": null,
   "eps_src": "Normalized",
   "offcycle": false,
   "price_eps_ccy": 459.88,
   "fy_labels": [
    2026,
    2027,
    2028
   ],
   "eps": [
    44.17,
    47.64,
    52.85
   ],
   "rev": [
    19287.3,
    20156.3,
    21127.5
   ],
   "n_est": [
    13,
    13,
    4
   ],
   "pe": [
    10.4,
    9.7,
    8.7
   ],
   "eps_cagr": 9.4,
   "rev_cagr": 4.7
  },
  {
   "id": "SCHW",
   "ticker": "SCHW US",
   "name": "The Charles Schwab Corporation",
   "sector": "Wealth / Brokers",
   "price": 90.95,
   "price_ccy": "USD",
   "eps_ccy": "USD",
   "fx": null,
   "eps_src": "Normalized",
   "offcycle": false,
   "price_eps_ccy": 90.95,
   "fy_labels": [
    2026,
    2027,
    2028
   ],
   "eps": [
    6.15,
    7.25,
    8.16
   ],
   "rev": [
    27265.4,
    29570.9,
    31834.4
   ],
   "n_est": [
    20,
    20,
    8
   ],
   "pe": [
    14.8,
    12.5,
    11.1
   ],
   "eps_cagr": 15.1,
   "rev_cagr": 8.1
  },
  {
   "id": "LPLA",
   "ticker": "LPLA US",
   "name": "LPL Financial Holdings Inc.",
   "sector": "Wealth / Brokers",
   "price": 295.32,
   "price_ccy": "USD",
   "eps_ccy": "USD",
   "fx": null,
   "eps_src": "Normalized",
   "offcycle": false,
   "price_eps_ccy": 295.32,
   "fy_labels": [
    2026,
    2027,
    2028
   ],
   "eps": [
    23.2,
    28.45,
    34.19
   ],
   "rev": [
    20575.2,
    23293.6,
    25425.6
   ],
   "n_est": [
    15,
    16,
    7
   ],
   "pe": [
    12.7,
    10.4,
    8.6
   ],
   "eps_cagr": 21.4,
   "rev_cagr": 11.2
  },
  {
   "id": "HOOD",
   "ticker": "HOOD US",
   "name": "Robinhood Markets, Inc.",
   "sector": "Wealth / Brokers",
   "price": 98.12,
   "price_ccy": "USD",
   "eps_ccy": "USD",
   "fx": null,
   "eps_src": "Normalized",
   "offcycle": false,
   "price_eps_ccy": 98.12,
   "fy_labels": [
    2026,
    2027,
    2028
   ],
   "eps": [
    2.17,
    2.8,
    3.56
   ],
   "rev": [
    5000.4,
    6093.9,
    6886.2
   ],
   "n_est": [
    6,
    6,
    4
   ],
   "pe": [
    45.2,
    35.0,
    27.5
   ],
   "eps_cagr": 28.2,
   "rev_cagr": 17.4
  },
  {
   "id": "IBKR",
   "ticker": "IBKR US",
   "name": "Interactive Brokers Group, Inc.",
   "sector": "Wealth / Brokers",
   "price": 92.76,
   "price_ccy": "USD",
   "eps_ccy": "USD",
   "fx": null,
   "eps_src": "Normalized",
   "offcycle": false,
   "price_eps_ccy": 92.76,
   "fy_labels": [
    2026,
    2027,
    2028
   ],
   "eps": [
    2.51,
    2.88,
    3.28
   ],
   "rev": [
    7046.8,
    7927.6,
    9426.6
   ],
   "n_est": [
    10,
    11,
    5
   ],
   "pe": [
    36.9,
    32.2,
    28.3
   ],
   "eps_cagr": 14.3,
   "rev_cagr": 15.7
  },
  {
   "id": "COIN",
   "ticker": "COIN US",
   "name": "Coinbase Global, Inc.",
   "sector": "Wealth / Brokers",
   "price": 169.62,
   "price_ccy": "USD",
   "eps_ccy": "USD",
   "fx": null,
   "eps_src": "Normalized",
   "offcycle": false,
   "price_eps_ccy": 169.62,
   "fy_labels": [
    2026,
    2027,
    2028
   ],
   "eps": [
    1.23,
    4.95,
    6.27
   ],
   "rev": [
    6154.0,
    7761.7,
    8319.9
   ],
   "n_est": [
    17,
    22,
    7
   ],
   "pe": [
    138.1,
    34.3,
    27.1
   ],
   "eps_cagr": 125.9,
   "rev_cagr": 16.3
  },
  {
   "id": "RJF",
   "ticker": "RJF US",
   "name": "Raymond James Financial, Inc.",
   "sector": "Wealth / Brokers",
   "price": 154.71,
   "price_ccy": "USD",
   "eps_ccy": "USD",
   "fx": null,
   "eps_src": "Normalized",
   "offcycle": false,
   "price_eps_ccy": 154.71,
   "fy_labels": [
    2026,
    2027,
    2028
   ],
   "eps": [
    11.86,
    13.37,
    14.34
   ],
   "rev": [
    15561.8,
    16731.3,
    17359.4
   ],
   "n_est": [
    13,
    13,
    4
   ],
   "pe": [
    13.0,
    11.6,
    10.8
   ],
   "eps_cagr": 9.9,
   "rev_cagr": 5.6
  },
  {
   "id": "SF",
   "ticker": "SF US",
   "name": "Stifel Financial Corp.",
   "sector": "Wealth / Brokers",
   "price": 73.18,
   "price_ccy": "USD",
   "eps_ccy": "USD",
   "fx": null,
   "eps_src": "Normalized",
   "offcycle": false,
   "price_eps_ccy": 73.18,
   "fy_labels": [
    2026,
    2027,
    2028
   ],
   "eps": [
    6.31,
    7.0,
    6.72
   ],
   "rev": [
    5996.6,
    6467.2,
    6614.3
   ],
   "n_est": [
    8,
    8,
    3
   ],
   "pe": [
    11.6,
    10.5,
    10.9
   ],
   "eps_cagr": 3.3,
   "rev_cagr": 5.0
  },
  {
   "id": "WLTH",
   "ticker": "WLTH US",
   "name": "Wealthfront Corporation",
   "sector": "Wealth / Brokers",
   "price": 8.8,
   "price_ccy": "USD",
   "eps_ccy": "USD",
   "fx": null,
   "eps_src": "Normalized",
   "offcycle": true,
   "price_eps_ccy": 8.8,
   "fy_labels": [
    2027,
    2028,
    2029
   ],
   "eps": [
    0.68,
    0.8,
    1.0
   ],
   "rev": [
    379.7,
    457.5,
    589.9
   ],
   "n_est": [
    4,
    4,
    1
   ],
   "pe": [
    12.9,
    11.1,
    8.8
   ],
   "eps_cagr": 21.3,
   "rev_cagr": 24.6
  },
  {
   "id": "ETOR",
   "ticker": "ETOR US",
   "name": "eToro Group Ltd.",
   "sector": "Wealth / Brokers",
   "price": 39.75,
   "price_ccy": "USD",
   "eps_ccy": "USD",
   "fx": null,
   "eps_src": "Normalized",
   "offcycle": false,
   "price_eps_ccy": 39.75,
   "fy_labels": [
    2026,
    2027,
    2028
   ],
   "eps": [
    2.81,
    3.25,
    3.77
   ],
   "rev": [
    965.0,
    1058.1,
    1106.9
   ],
   "n_est": [
    12,
    12,
    6
   ],
   "pe": [
    14.1,
    12.2,
    10.5
   ],
   "eps_cagr": 15.8,
   "rev_cagr": 7.1
  },
  {
   "id": "SWX:SQN",
   "ticker": "SQ SW",
   "name": "Swissquote Group Holding SA",
   "sector": "Wealth / Brokers",
   "price": 40.0,
   "price_ccy": "CHF",
   "eps_ccy": "CHF",
   "fx": null,
   "eps_src": "Normalized",
   "offcycle": false,
   "price_eps_ccy": 40.0,
   "fy_labels": [
    2026,
    2027,
    2028
   ],
   "eps": [
    2.22,
    2.51,
    2.88
   ],
   "rev": [
    761.2,
    834.0,
    929.4
   ],
   "n_est": [
    11,
    11,
    7
   ],
   "pe": [
    18.0,
    16.0,
    13.9
   ],
   "eps_cagr": 13.8,
   "rev_cagr": 10.5
  },
  {
   "id": "XTRA:FTK",
   "ticker": "FTK GY",
   "name": "flatexDEGIRO SE",
   "sector": "Wealth / Brokers",
   "price": 37.04,
   "price_ccy": "EUR",
   "eps_ccy": "EUR",
   "fx": null,
   "eps_src": "Normalized",
   "offcycle": false,
   "price_eps_ccy": 37.04,
   "fy_labels": [
    2026,
    2027,
    2028
   ],
   "eps": [
    1.9,
    2.28,
    2.62
   ],
   "rev": [
    626.9,
    700.5,
    782.8
   ],
   "n_est": [
    11,
    11,
    10
   ],
   "pe": [
    19.5,
    16.3,
    14.1
   ],
   "eps_cagr": 17.4,
   "rev_cagr": 11.7
  },
  {
   "id": "BIT:BGN",
   "ticker": "BGN IM",
   "name": "Banca Generali S.p.A.",
   "sector": "Wealth / Brokers",
   "price": 63.8,
   "price_ccy": "EUR",
   "eps_ccy": "EUR",
   "fx": null,
   "eps_src": "Normalized",
   "offcycle": false,
   "price_eps_ccy": 63.8,
   "fy_labels": [
    2026,
    2027,
    2028
   ],
   "eps": [
    3.54,
    3.71,
    3.87
   ],
   "rev": [
    1052.2,
    1097.8,
    1154.3
   ],
   "n_est": [
    6,
    6,
    6
   ],
   "pe": [
    18.0,
    17.2,
    16.5
   ],
   "eps_cagr": 4.7,
   "rev_cagr": 4.7
  },
  {
   "id": "BIT:FBK",
   "ticker": "FBK IM",
   "name": "FinecoBank Banca Fineco S.p.A.",
   "sector": "Wealth / Brokers",
   "price": 22.23,
   "price_ccy": "EUR",
   "eps_ccy": "EUR",
   "fx": null,
   "eps_src": "Normalized",
   "offcycle": false,
   "price_eps_ccy": 22.23,
   "fy_labels": [
    2026,
    2027,
    2028
   ],
   "eps": [
    1.09,
    1.21,
    1.34
   ],
   "rev": [
    1433.9,
    1575.8,
    1716.2
   ],
   "n_est": [
    15,
    15,
    14
   ],
   "pe": [
    20.4,
    18.3,
    16.6
   ],
   "eps_cagr": 10.8,
   "rev_cagr": 9.4
  },
  {
   "id": "CRCL",
   "ticker": "CRCL US",
   "name": "Circle Internet Group, Inc.",
   "sector": "Wealth / Brokers",
   "price": 83.37,
   "price_ccy": "USD",
   "eps_ccy": "USD",
   "fx": null,
   "eps_src": "Normalized",
   "offcycle": false,
   "price_eps_ccy": 83.37,
   "fy_labels": [
    2026,
    2027,
    2028
   ],
   "eps": [
    1.25,
    2.23,
    3.1
   ],
   "rev": [
    3072.6,
    4308.9,
    5442.0
   ],
   "n_est": [
    8,
    12,
    5
   ],
   "pe": [
    66.6,
    37.4,
    26.9
   ],
   "eps_cagr": 57.4,
   "rev_cagr": 33.1
  },
  {
   "id": "FIGR",
   "ticker": "FIGR US",
   "name": "Figure Technology Solutions, Inc.",
   "sector": "Wealth / Brokers",
   "price": 28.99,
   "price_ccy": "USD",
   "eps_ccy": "USD",
   "fx": null,
   "eps_src": "Normalized",
   "offcycle": false,
   "price_eps_ccy": 28.99,
   "fy_labels": [
    2026,
    2027,
    2028
   ],
   "eps": [
    1.19,
    1.39,
    1.66
   ],
   "rev": [
    811.5,
    976.7,
    1200.2
   ],
   "n_est": [
    4,
    4,
    1
   ],
   "pe": [
    24.4,
    20.9,
    17.5
   ],
   "eps_cagr": 18.2,
   "rev_cagr": 21.6
  }
 ]
};
